In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
USAFacts_C = pd.read_csv('../../../data/us/covid/confirmed_cases.csv')
USAFacts_D = pd.read_csv('../../../data/us/covid/deaths.csv')
JHU_DC = pd.read_csv('../../../data/us/covid/JHU_daily_US.csv')
Tests = pd.read_csv('../../../data/us/covid/daily_state_tests.csv')
NYTStates_DC = pd.read_csv('../../../data/us/covid/nyt_us_states.csv')
NYTCounties_DC = pd.read_csv('../../../data/us/covid/nyt_us_counties.csv')

In [3]:
LAT_Agency = pd.read_csv('../../../data/us/covid/california/latimes-agency-totals.csv')
LAT_Place = pd.read_csv('../../../data/us/covid/california/latimes-place-totals.csv')
CDPH_State_Totals = pd.read_csv('../../../data/us/covid/california/cdph-state-totals.csv')

In [4]:
Key = pd.read_csv('../../../data/us/processing_data/fips_key.csv', encoding='latin1')

In [5]:
NYTCounties_DC.sort_values(by=['fips'])

,date,county,state,fips,cases,deaths
14046,2020-03-27,Autauga,Alabama,1001.0,6,0
30844,2020-04-04,Autauga,Alabama,1001.0,12,0
21800,2020-03-31,Autauga,Alabama,1001.0,7,0
38181,2020-04-07,Autauga,Alabama,1001.0,12,1
26198,2020-04-02,Autauga,Alabama,1001.0,10,0
17731,2020-03-29,Autauga,Alabama,1001.0,6,0
33249,2020-04-05,Autauga,Alabama,1001.0,12,0
12377,2020-03-26,Autauga,Alabama,1001.0,6,0
19714,2020-03-30,Autauga,Alabama,1001.0,7,0
10839,2020-03-25,Autauga,Alabama,1001.0,4,0
15836,2020-03-28,Autauga,Alabama,1001.0,6,0
23967,2020-04-01,Autauga,Alabama,1001.0,10,0
35692,2020-04-06,Autauga,Alabama,1001.0,12,1
9481,2020-03-24,Autauga,Alabama,1001.0,1,0
28488,2020-04-03,Autauga,Alabama,1001.0,12,0
8254,2020-03-23,Baldwin,Alabama,1003.0,3,0
14047,2020-03-27,Baldwin,Alabama,1003.0,5,0
10840,2020-03-25,Baldwin,Alabama,1003.0,4,0
23968,2020-04-01,Baldwin,Alabama,1003.0,23,1
26199,2020-04-02,Baldwin,Alabama,1003.0,25,1
7116,2020-03-22,Baldwin,Alabama,1003.0,2,0
9482,2020-03-24,Baldwin,Alabama,1003.0,4,0
19715,2020-03-30,Baldwin,Alabama,1003.0,18,0
30845,2020-04-04,Baldwin,Alabama,1003.0,29,1
6082,2020-03-21,Baldwin,Alabama,1003.0,2,0
38182,2020-04-07,Baldwin,Alabama,1003.0,42,1
5166,2020-03-20,Baldwin,Alabama,1003.0,2,0
17732,2020-03-29,Baldwin,Alabama,1003.0,15,0
4400,2020-03-19,Baldwin,Alabama,1003.0,1,0
33250,2020-04-05,Baldwin,Alabama,1003.0,34,1
...,...,...,...,...,...,...
37917,2020-04-06,Unknown,Virgin Islands,NaN,43,1
38021,2020-04-06,Unknown,Virginia,NaN,0,18
38064,2020-04-06,Unknown,Washington,NaN,653,0
38269,2020-04-07,Unknown,Arizona,NaN,0,12
38335,2020-04-07,Unknown,Arkansas,NaN,11,0
38445,2020-04-07,Unknown,Colorado,NaN,249,0
38456,2020-04-07,Unknown,Connecticut,NaN,292,3
38523,2020-04-07,Unknown,Florida,NaN,2,0
38668,2020-04-07,Unknown,Georgia,NaN,441,6
38684,2020-04-07,Unknown,Guam,NaN,274,4
38689,2020-04-07,Unknown,Hawaii,NaN,7,0
38791,2020-04-07,Unknown,Illinois,NaN,34,0
39170,2020-04-07,Unknown,Louisiana,NaN,49,2
39191,2020-04-07,Unknown,Maine,NaN,9,0
39232,2020-04-07,Unknown,Massachusetts,NaN,229,8
39302,2020-04-07,Unknown,Michigan,NaN,405,0
39490,2020-04-07,Kansas City,Missouri,NaN,219,7
39532,2020-04-07,Unknown,Missouri,NaN,2,0
39614,2020-04-07,Unknown,New Hampshire,NaN,1,0
39635,2020-04-07,Unknown,New Jersey,NaN,2220,5
39688,2020-04-07,New York City,New York,NaN,76876,4009
39835,2020-04-07,Unknown,Northern Mariana Islands,NaN,8,2
40074,2020-04-07,Unknown,Puerto Rico,NaN,573,23
40079,2020-04-07,Unknown,Rhode Island,NaN,223,13
40157,2020-04-07,Unknown,South Dakota,NaN,0,4
40425,2020-04-07,Unknown,Utah,NaN,0,9
40440,2020-04-07,Unknown,Vermont,NaN,3,16
40444,2020-04-07,Unknown,Virgin Islands,NaN,45,1
40553,2020-04-07,Unknown,Virginia,NaN,0,26
40596,2020-04-07,Unknown,Washington,NaN,601,0

In [6]:
JHU_DC.sort_values(by=['FIPS'])

          FIPS  Confirmed  Deaths  Recovered  Active        Date
22113   1001.0          6       0          0       0  03-30-2020
36545   1001.0         12       0          0       0  04-05-2020
15829   1001.0          6       0          0       0  03-28-2020
27347   1001.0          8       0          0       0  04-01-2020
12686   1001.0          6       0          0       0  03-27-2020
6399    1001.0          4       0          0       0  03-25-2020
34148   1001.0         12       0          0       0  04-04-2020
25224   1001.0          7       0          0       0  03-31-2020
39022   1001.0         12       0          0       0  04-06-2020
18971   1001.0          6       0          0       0  03-29-2020
110     1001.0          0       0          0       0  03-23-2020
29520   1001.0         10       0          0       0  04-02-2020
9543    1001.0          6       0          0       0  03-26-2020
3255    1001.0          1       0          0       0  03-24-2020
31803   1001.0         12       0          0       0  04-03-2020
22122   1003.0         18       1          0       0  03-30-2020
12695   1003.0          5       0          0       0  03-27-2020
29526   1003.0         24       1          0       0  04-02-2020
27353   1003.0         20       1          0       0  04-01-2020
9552    1003.0          5       0          0       0  03-26-2020
15838   1003.0         10       0          0       0  03-28-2020
6408    1003.0          4       0          0       0  03-25-2020
119     1003.0          3       0          0       0  03-23-2020
39028   1003.0         38       1          0       0  04-06-2020
36551   1003.0         29       1          0       0  04-05-2020
31809   1003.0         28       1          0       0  04-03-2020
3264    1003.0          4       0          0       0  03-24-2020
25230   1003.0         19       1          0       0  03-31-2020
18980   1003.0         15       1          0       0  03-29-2020
34154   1003.0         29       1          0       0  04-04-2020
...        ...        ...     ...        ...     ...         ...
31487  90046.0          0       0          0       0  04-02-2020
33819  90046.0          0       0          0       0  04-03-2020
41200  90047.0         69       0          0       0  04-06-2020
36215  90047.0         63       0          0       0  04-04-2020
38685  90047.0         86       0          0       0  04-05-2020
33820  90047.0         54       0          0       0  04-03-2020
31488  90047.0          6       0          0       0  04-02-2020
38686  90049.0          2       0          0       0  04-05-2020
41201  90049.0          0       0          0       0  04-06-2020
41202  90050.0         21      18          0       0  04-06-2020
36216  90050.0         11      15          0       0  04-04-2020
33821  90050.0          6      12          0       0  04-03-2020
38687  90050.0         13      17          0       0  04-05-2020
31489  90050.0          5      12          0       0  04-02-2020
41203  90051.0          0      50          0       0  04-06-2020
36217  90051.0          0      36          0       0  04-04-2020
33822  90051.0          0      31          0       0  04-03-2020
38688  90051.0          3      36          0       0  04-05-2020
31490  90051.0          0      26          0       0  04-02-2020
38689  90053.0        533       0          0       0  04-05-2020
33823  90053.0        501       0          0       0  04-03-2020
41204  90053.0        648       0          0       0  04-06-2020
36218  90053.0        483       0          0       0  04-04-2020
31491  90053.0        344       0          0       0  04-02-2020
31492  90054.0          0       1          0       0  04-02-2020
31493  90055.0          0       5          0       0  04-02-2020
33824  90055.0          0       4          0       0  04-03-2020
36219  90055.0          0       4          0       0  04-04-2020
38690  90055.0          0       0          0       0  04-05-2020
41205  90055.0          0       0          0       0  04-06-2020

[41450 rows x 6 columns]

In [7]:
JHU_DC

          FIPS  Confirmed  Deaths  Recovered  Active        Date
0      45001.0          1       0          0       0  03-23-2020
1      22001.0          1       0          0       0  03-23-2020
2      51001.0          1       0          0       0  03-23-2020
3      16001.0         13       0          0       0  03-23-2020
4      19001.0          1       0          0       0  03-23-2020
5      21001.0          0       0          0       0  03-23-2020
6      29001.0          2       0          0       0  03-23-2020
7      40001.0          0       0          0       0  03-23-2020
8       8001.0         18       0          0       0  03-23-2020
9      16003.0          0       0          0       0  03-23-2020
10     17001.0          1       0          0       0  03-23-2020
11     18001.0          1       0          0       0  03-23-2020
12     19003.0          0       0          0       0  03-23-2020
13     28001.0          2       0          0       0  03-23-2020
14     31001.0          1       0          0       0  03-23-2020
15     38001.0          0       0          0       0  03-23-2020
16     39001.0          0       0          0       0  03-23-2020
17     42001.0          6       0          0       0  03-23-2020
18     53001.0          1       0          0       0  03-23-2020
19     55001.0          0       0          0       0  03-23-2020
20     50001.0          6       0          0       0  03-23-2020
21     45003.0          1       0          0       0  03-23-2020
22     27001.0          0       0          0       0  03-23-2020
23     12001.0         36       0          0       0  03-23-2020
24     37001.0          2       0          0       0  03-23-2020
25      6001.0        118       1          0       0  03-23-2020
26      8003.0          0       0          0       0  03-23-2020
27     36001.0        127       0          0       0  03-23-2020
28     56001.0          0       0          0       0  03-23-2020
29     51003.0          2       0          0       0  03-23-2020
...        ...        ...     ...        ...     ...         ...
41420  27171.0          9       0          0       0  04-06-2020
41421  29229.0          7       0          0       0  04-06-2020
41422  39175.0          5       0          0       0  04-06-2020
41423  20209.0        186       6          0       0  04-06-2020
41424  36121.0         23       1          0       0  04-06-2020
41425  42131.0          5       0          0       0  04-06-2020
41426  51197.0          3       0          0       0  04-06-2020
41427  37197.0          9       0          0       0  04-06-2020
41428  53077.0        363      12          0       0  04-06-2020
41429  28161.0         11       0          0       0  04-06-2020
41430  41071.0         26       3          0       0  04-06-2020
41431  46135.0         18       0          0       0  04-06-2020
41432  36123.0          1       0          0       0  04-06-2020
41433   4025.0         49       0          0       0  04-06-2020
41434  28163.0         32       1          0       0  04-06-2020
41435   5149.0          1       0          0       0  04-06-2020
41436  27173.0          1       0          0       0  04-06-2020
41437  30111.0         40       0          0       0  04-06-2020
41438   6113.0         37       1          0       0  04-06-2020
41439  23031.0        108       1          0       0  04-06-2020
41440  31185.0          1       0          0       0  04-06-2020
41441  42133.0        189       1          0       0  04-06-2020
41442  45091.0         95       2          0       0  04-06-2020
41443  51199.0         21       1          0       0  04-06-2020
41444  48503.0          3       0          0       0  04-06-2020
41445   6115.0         11       0          0       0  04-06-2020
41446   2290.0          1       0          0       0  04-06-2020
41447   4027.0         13       0          0       0  04-06-2020
41448   8125.0          2       0          0       0  04-06-2020
41449  48505.0          1       0          0       0  04-06-2020

[41450 rows x 6 columns]