In [547]:
import pandas as pd
import numpy as np
import os

In [548]:
USAFacts_C = pd.read_csv('../../../data/us/covid/confirmed_cases.csv')
USAFacts_D = pd.read_csv('../../../data/us/covid/deaths.csv')
JHU_CD = pd.read_csv('../../../data/us/covid/JHU_daily_US.csv')
Tests = pd.read_csv('../../../data/us/covid/daily_state_tests.csv')
NYTStates_CD = pd.read_csv('../../../data/us/covid/nyt_us_states.csv')
NYTCounties_CD = pd.read_csv('../../../data/us/covid/nyt_us_counties.csv')

In [549]:
LAT_Agency = pd.read_csv('../../../data/us/covid/california/latimes-agency-totals.csv')
LAT_Place = pd.read_csv('../../../data/us/covid/california/latimes-place-totals.csv')
CDPH_State_Totals = pd.read_csv('../../../data/us/covid/california/cdph-state-totals.csv')

In [550]:
def delete_zero_columns(frame): #Delete Columns containing only 0s
    cols = list(frame.columns)
    for col in cols:
        if (frame[col] == 0).all():
            frame = frame.drop(columns=[col])
    return frame

In [551]:
#Removing Statewide Unallocated Lines
USAFacts_C = USAFacts_C[USAFacts_C['County Name'] != 'Statewide Unallocated']
USAFacts_D = USAFacts_D[USAFacts_D['County Name'] != 'Statewide Unallocated']
#Merging Cases and Deaths
USAFacts_CD = pd.merge(USAFacts_C, USAFacts_D, left_on='countyFIPS', right_on='countyFIPS', suffixes=('_C', '_D'))
USAFacts_CD = USAFacts_CD.drop(columns=['County Name_D', 'State_D', 'stateFIPS_D'])
USAFacts_CD_NC = USAFacts_CD
USAFacts_CD.to_csv('USAFacts_CDNonConsecutive.csv') #csv of Fips, All Dates of Cases, All Dates of Deaths

Beg = list(USAFacts_CD.columns[:4]) #First four entries
End = list(np.sort(np.array(USAFacts_CD.columns[4:]))) #Every Date Sorted
cols = list(Beg + End) #Ordered Columns

USAFacts_CD = USAFacts_CD[cols]

USAFacts_CD.to_csv('USAFacts_CDConsecutive.csv') #Csv of FIps, each date and the number of cases & deaths

In [552]:
USAFacts_CD_NC.head()

,countyFIPS,County Name_C,State_C,stateFIPS_C,1/22/20_C,1/23/20_C,1/24/20_C,1/25/20_C,1/26/20_C,1/27/20_C,...,3/29/20_D,3/30/20_D,3/31/20_D,4/1/20_D,4/2/20_D,4/3/20_D,4/4/20_D,4/5/20_D,4/6/20_D,4/7/20_D
0,1001,Autauga County,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1005,Barbour County,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1007,Bibb County,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1009,Blount County,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [553]:
USAFacts_CD.head()

,countyFIPS,County Name_C,State_C,stateFIPS_C,1/22/20_C,1/22/20_D,1/23/20_C,1/23/20_D,1/24/20_C,1/24/20_D,...,4/3/20_C,4/3/20_D,4/4/20_C,4/4/20_D,4/5/20_C,4/5/20_D,4/6/20_C,4/6/20_D,4/7/20_C,4/7/20_D
0,1001,Autauga County,AL,1,0,0,0,0,0,0,...,12,0,12,0,12,0,12,0,12,0
1,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,28,0,29,0,34,0,38,0,42,0
2,1005,Barbour County,AL,1,0,0,0,0,0,0,...,1,0,2,0,2,0,3,0,3,0
3,1007,Bibb County,AL,1,0,0,0,0,0,0,...,4,0,4,0,7,0,7,0,8,0
4,1009,Blount County,AL,1,0,0,0,0,0,0,...,9,0,10,0,10,0,10,0,10,0

In [554]:
JHU_CD = JHU_CD[JHU_CD.FIPS <= 60000]
JHU_CD = pd.pivot_table(JHU_CD, values=['Confirmed', 'Deaths'], index=['FIPS'], columns=['Date'])
JHU_CD = pd.DataFrame(JHU_CD)
JHU_CD = JHU_CD.fillna(0)
JHU_CD.to_csv('JHU_CD.csv')

In [555]:
JHU_CD.head()

        Confirmed                                                         \
Date   03-23-2020 03-24-2020 03-25-2020 03-26-2020 03-27-2020 03-28-2020
FIPS
1001.0        0.0        1.0        4.0        6.0        6.0        6.0
1003.0        3.0        4.0        4.0        5.0        5.0       10.0
1005.0        0.0        0.0        0.0        0.0        0.0        0.0
1007.0        0.0        0.0        0.0        0.0        0.0        0.0
1009.0        0.0        0.0        1.0        2.0        4.0        5.0

                                                    ...     Deaths             \
Date   03-29-2020 03-30-2020 03-31-2020 04-01-2020  ... 03-28-2020 03-29-2020
FIPS                                                ...
1001.0        6.0        6.0        7.0        8.0  ...        0.0        0.0
1003.0       15.0       18.0       19.0       20.0  ...        0.0        1.0
1005.0        0.0        0.0        0.0        0.0  ...        0.0        0.0
1007.0        0.0        2.0        3.0        3.0  ...        0.0        0.0
1009.0        5.0        5.0        5.0        5.0  ...        0.0        0.0

                                                                          \
Date   03-30-2020 03-31-2020 04-01-2020 04-02-2020 04-03-2020 04-04-2020
FIPS
1001.0        0.0        0.0        0.0        0.0        0.0        0.0
1003.0        1.0        1.0        1.0        1.0        1.0        1.0
1005.0        0.0        0.0        0.0        0.0        0.0        0.0
1007.0        0.0        0.0        0.0        0.0        0.0        0.0
1009.0        0.0        0.0        0.0        0.0        0.0        0.0


Date   04-05-2020 04-06-2020
FIPS
1001.0        0.0        0.0
1003.0        1.0        1.0
1005.0        0.0        0.0
1007.0        0.0        0.0
1009.0        0.0        0.0

[5 rows x 30 columns]

In [556]:
NYTCounties_CD = NYTCounties_CD.sort_values(by=['fips', 'date'])
NYTCounties_CD = NYTCounties_CD[NYTCounties_CD.fips <= 95000]
NYTCounties_CD = pd.pivot_table(NYTCounties_CD, values=['cases', 'deaths'], index=['fips'], columns=['date'])
NYTCounties_CD = NYTCounties_CD.fillna(0)
NYTCounties_CD.to_csv('NYTCounties_CD.csv')

In [557]:
NYTCounties_CD.head()

            cases                                                         \
date   2020-01-21 2020-01-22 2020-01-23 2020-01-24 2020-01-25 2020-01-26
fips
1001.0        0.0        0.0        0.0        0.0        0.0        0.0
1003.0        0.0        0.0        0.0        0.0        0.0        0.0
1005.0        0.0        0.0        0.0        0.0        0.0        0.0
1007.0        0.0        0.0        0.0        0.0        0.0        0.0
1009.0        0.0        0.0        0.0        0.0        0.0        0.0

                                                    ...     deaths             \
date   2020-01-27 2020-01-28 2020-01-29 2020-01-30  ... 2020-03-29 2020-03-30
fips                                                ...
1001.0        0.0        0.0        0.0        0.0  ...        0.0        0.0
1003.0        0.0        0.0        0.0        0.0  ...        0.0        0.0
1005.0        0.0        0.0        0.0        0.0  ...        0.0        0.0
1007.0        0.0        0.0        0.0        0.0  ...        0.0        0.0
1009.0        0.0        0.0        0.0        0.0  ...        0.0        0.0

                                                                          \
date   2020-03-31 2020-04-01 2020-04-02 2020-04-03 2020-04-04 2020-04-05
fips
1001.0        0.0        0.0        0.0        0.0        0.0        0.0
1003.0        0.0        1.0        1.0        1.0        1.0        1.0
1005.0        0.0        0.0        0.0        0.0        0.0        0.0
1007.0        0.0        0.0        0.0        0.0        0.0        0.0
1009.0        0.0        0.0        0.0        0.0        0.0        0.0


date   2020-04-06 2020-04-07
fips
1001.0        1.0        1.0
1003.0        1.0        1.0
1005.0        0.0        0.0
1007.0        0.0        0.0
1009.0        0.0        0.0

[5 rows x 156 columns]

In [558]:
print('USAFacts_CD: ' + str(len(USAFacts_CD)))
print('JHU_CD: ' + str(len(JHU_CD)))
print('NYTCounties_CD: ' + str(len(NYTCounties_CD)))

USAFacts_CD: 3145
JHU_CD: 3142
NYTCounties_CD: 2532

In [559]:
Tests = Tests.sort_values(by=['fips', 'date'])
Tests

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
1697,20200307,AL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,1,NaN,NaN,NaN,NaN,NaN
1646,20200308,AL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,1,0.0,0.0,0.0,0.0,0.0
1595,20200309,AL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,1,0.0,0.0,0.0,0.0,0.0
1544,20200310,AL,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,0,1,0.0,0.0,0.0,0.0,0.0
1493,20200311,AL,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10,10,10,1,0.0,0.0,10.0,0.0,10.0
1442,20200312,AL,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,10,10,10,1,0.0,0.0,0.0,0.0,0.0
1391,20200313,AL,1.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,12,12,12,1,0.0,0.0,1.0,1.0,2.0
1340,20200314,AL,6.0,22.0,46.0,NaN,NaN,NaN,NaN,NaN,...,NaN,74,28,28,1,0.0,0.0,11.0,5.0,16.0
1289,20200315,AL,12.0,28.0,46.0,NaN,NaN,NaN,NaN,NaN,...,NaN,86,40,40,1,0.0,0.0,6.0,6.0,12.0
1233,20200316,AL,28.0,28.0,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,96,56,56,1,0.0,0.0,0.0,16.0,16.0
1177,20200317,AL,36.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,64,64,64,1,0.0,0.0,0.0,8.0,8.0
1121,20200318,AL,46.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,74,74,74,1,0.0,0.0,0.0,10.0,10.0
1065,20200319,AL,68.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,96,96,96,1,0.0,0.0,0.0,22.0,22.0
1009,20200320,AL,81.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,109,109,109,1,0.0,0.0,0.0,13.0,13.0
953,20200321,AL,124.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,152,152,152,1,0.0,0.0,0.0,43.0,43.0
897,20200322,AL,138.0,1464.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1602,1602,1602,1,0.0,0.0,1436.0,14.0,1450.0
841,20200323,AL,167.0,1665.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1832,1832,1832,1,0.0,0.0,201.0,29.0,230.0
785,20200324,AL,215.0,2106.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2321,2321,2321,1,0.0,0.0,441.0,48.0,489.0
729,20200325,AL,283.0,2529.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2812,2812,2812,1,0.0,0.0,423.0,68.0,491.0
673,20200326,AL,506.0,3593.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4099,4099,4099,1,1.0,0.0,1064.0,223.0,1287.0
617,20200327,AL,587.0,4184.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4771,4771,4771,1,2.0,0.0,591.0,81.0,672.0
561,20200328,AL,696.0,4184.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4880,4880,4880,1,0.0,0.0,0.0,109.0,109.0
505,20200329,AL,806.0,4184.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4990,4990,4990,1,1.0,0.0,0.0,110.0,110.0
449,20200330,AL,859.0,5694.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6553,6553,6553,1,2.0,0.0,1510.0,53.0,1563.0
393,20200331,AL,981.0,6298.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7279,7279,7279,1,7.0,0.0,604.0,122.0,726.0
337,20200401,AL,1077.0,6697.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7774,7774,7774,1,13.0,0.0,399.0,96.0,495.0
281,20200402,AL,1233.0,7503.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8736,8736,8736,1,6.0,0.0,806.0,156.0,962.0
225,20200403,AL,1432.0,8187.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9619,9619,9619,1,3.0,0.0,684.0,199.0,883.0
169,20200404,AL,1580.0,9273.0,NaN,NaN,212.0,NaN,NaN,NaN,...,212.0,10853,10853,10853,1,8.0,212.0,1086.0,148.0,1234.0
113,20200405,AL,1796.0,11282.0,NaN,NaN,231.0,NaN,NaN,NaN,...,231.0,13078,13078,13078,1,2.0,19.0,2009.0,216.0,2225.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,20200401,PR,286.0,1409.0,897.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2592,1695,1695,72,3.0,0.0,214.0,47.0,261.0
322,20200402,PR,316.0,1604.0,1119.0,NaN,NaN,NaN,NaN,NaN,...,NaN,3039,1920,1920,72,1.0,0.0,195.0,30.0,225.0
266,20200403,PR,378.0,2049.0,1055.0,NaN,NaN,NaN,NaN,NaN,...,NaN,3482,2427,2427,72,3.0,0.0,445.0,62.0,507.0
210,20200404,PR,452.0,2605.0,1129.0,NaN,NaN,NaN,NaN,NaN,...,NaN,4186,3057,3057,72,3.0,0.0,556.0,74.0,630.0
154,20200405,PR,475.0,3073.0,1039.0,NaN,NaN,NaN,NaN,NaN,...,NaN,4587,3548,3548,72,2.0,0.0,468.0,23.0,491.0
98,20200406,PR,513.0,3432.0,1000.0,NaN,NaN,NaN,NaN,NaN,...,NaN,4945,3945,3945,72,1.0,0.0,359.0,38.0,397.0
42,20200407,PR,573.0,3966.0,968.0,NaN,NaN,NaN,NaN,NaN,...,NaN,5507,4539,4539,72,2.0,0.0,534.0,60.0,594.0
1282,20200316,VI,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,78,NaN,NaN,NaN,NaN,NaN
1226,20200317,VI,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2,2,2,78,0.0,0.0,0.0,1.0,1.0
1170,20200318,VI,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2,2,2,78,0.0,0.0,0.0,0.0,0.0
1114,20200319,VI,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3,3,3,78,0.0,0.0,0.0,1.0,1.0
1058,20200320,VI,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3,3,3,78,0.0,0.0,0.0,0.0,0.0
1002,20200321,VI,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6,6,6,78,0.0,0.0,0.0,3.0,3.0
946,20200322,VI,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6,6,6,78,0.0,0.0,0.0,0.0,0.0
890,20200323,VI,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17,17,17,78,0.0,0.0,0.0,11.0,11.0
834,20200324,VI,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17,17,17,78,0.0,0.0,0.0,0.0,0.0
778,20200325,VI,17.0,55.0,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,74,72,72,78,0.0,0.0,55.0,0.0,55.0
722,20200326,VI,17.0,55.0,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,74,72,72,78,0.0,0.0,0.0,0.0,0.0
666,20200327,VI,19.0,55.0,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,76,74,74,78,0.0,0.0,0.0,2.0,2.0
610,20200328,VI,22.0,106.0,55.0,NaN,NaN,NaN,NaN,NaN,...,NaN,183,128,128,78,0.0,0.0,51.0,3.0,54.0
554,20200329,VI,23.0,123.0,37.0,NaN,NaN,NaN,NaN,NaN,...,NaN,183,146,146,78,0.0,0.0,17.0,1.0,18.0
498,20200330,VI,30.0,126.0,24.0,NaN,NaN,NaN,NaN,NaN,...,NaN,180,156,156,78,0.0,0.0,3.0,7.0,10.0
442,20200331,VI,30.0,126.0,24.0,NaN,NaN,NaN,NaN,NaN,...,NaN,180,156,156,78,0.0,0.0,0.0,0.0,0.0
386,20200401,VI,30.0,126.0,24.0,NaN,NaN,NaN,NaN,NaN,...,NaN,180,156,156,78,0.0,0.0,0.0,0.0,0.0
330,20200402,VI,33.0,149.0,42.0,NaN,NaN,NaN,NaN,NaN,...,NaN,224,182,182,78,0.0,0.0,23.0,3.0,26.0
274,20200403,VI,38.0,154.0,56.0,NaN,NaN,NaN,NaN,NaN,...,NaN,248,192,192,78,0.0,0.0,5.0,5.0,10.0
218,20200404,VI,40.0,184.0,42.0,NaN,NaN,NaN,NaN,NaN,...,NaN,266,224,224,78,0.0,0.0,30.0,2.0,32.0
162,20200405,VI,42.0,206.0,18.0,NaN,NaN,NaN,NaN,NaN,...,NaN,266,248,248,78,1.0,0.0,22.0,2.0,24.0
106,20200406,VI,43.0,222.0,20.0,NaN,NaN,NaN,NaN,NaN,...,NaN,285,265,265,78,0.0,0.0,16.0,1.0,17.0
50,20200407,VI,43.0,222.0,20.0,NaN,NaN,NaN,NaN,NaN,...,NaN,285,265,265,78,0.0,0.0,0.0,0.0,0.0