In [15]:
import pandas as pd
import numpy as np
import os

In [16]:
County_Pop_Pop60 = pd.read_csv('../../../data/us/demographics/county_populations.csv', encoding='latin1')
Area_Houses = pd.read_csv('../../../data/us/demographics/county_land_areas.csv', encoding='latin1')
Educ = pd.read_csv('../../../data/us/demographics/education.csv', encoding='latin1')
Unemp = pd.read_csv('../../../data/us/demographics/unemployment.csv', delimiter="\t")
Poverty = pd.read_csv('../../../data/us/demographics/poverty.csv', delimiter="\t")

Age_Race = pd.read_csv('Age_Race.csv', encoding='latin1')

Votes = pd.read_csv('Votes.csv', encoding='latin1')
#Cleaning Votes
Votes = Votes.drop([0,1])
Votes.columns = ['FIPS', 'Total_2000', 'Total_2004', 'Total_2008', 'Total_2012', 'Total_2016', \
                 'Dem_2000', 'Dem_2004', 'Dem_2008', 'Dem_2012', 'Dem_2016']
Votes.FIPS = Votes.FIPS.astype(str).astype(float).astype(int)

County_Health = pd.read_csv('County_Health.csv', encoding='latin1')

Policies = pd.read_csv('../../../data/us/other/policies.csv', encoding='latin1')
Transit = pd.read_csv('../../../data/us/other/transit.csv', encoding='latin1')

Policy_Transit = pd.read_csv('Policy_Transit.csv', encoding='latin1')

USAFacts_CDConsecutive = pd.read_csv('USAFacts_CDConsecutive.csv', encoding='latin1')
USAFacts_CDNonConsecutive = pd.read_csv('USAFacts_CDNonConsecutive.csv', encoding='latin1')
USAFacts_CDConsecutive = USAFacts_CDConsecutive.drop(columns=['Unnamed: 0', 'County Name_C', 'State_C'])
USAFacts_CDNonConsecutive = USAFacts_CDNonConsecutive.drop(columns=['Unnamed: 0', 'County Name_C', 'State_C'])

In [17]:
print('County_Pop_Pop60: ' + str(len(County_Pop_Pop60)))
print('Area_Houses: ' + str(len(Area_Houses)))
print('Educ: ' + str(len(Educ)))
print('Unemp: ' + str(len(Unemp)))
print('Poverty: ' + str(len(Poverty)) + '\n')

print('Votes: ' + str(len(Votes)) + '\n')
print('Age_Race: ' + str(len(Age_Race)) + '\n')

print('County_Health: ' + str(len(County_Health)) + '\n')

print('Policies: ' + str(len(Policies)))
print('Transit: ' + str(len(Transit)) + '\n')
print('Policy_Transit: ' + str(len(Policy_Transit)) + '\n')

print('USAFacts_CDConsecutive: ' + str(len(USAFacts_CDConsecutive)))
print('USAFacts_CDNonConsecutive: ' + str(len(USAFacts_CDNonConsecutive)))

County_Pop_Pop60: 3142
Area_Houses: 3221
Educ: 3283
Unemp: 3141
Poverty: 3136

Votes: 3155

Age_Race: 838

County_Health: 3143

Policies: 3273
Transit: 3139

Policy_Transit: 3134

USAFacts_CDConsecutive: 3145
USAFacts_CDNonConsecutive: 3145

In [18]:
Policies

,FIPS,STATE,AREA_NAME,stay at home,>50 gatherings,>500 gatherings,public schools,restaurant dine-in,entertainment/gym,federal guidelines,foreign travel ban
0,0,US,united states,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000,AL,alabama,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
2,1001,AL,autauga county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
3,1003,AL,baldwin county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
4,1005,AL,barbour county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
5,1007,AL,bibb county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
6,1009,AL,blount county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
7,1011,AL,bullock county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
8,1013,AL,butler county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
9,1015,AL,calhoun county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
10,1017,AL,chambers county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
11,1019,AL,cherokee county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
12,1021,AL,chilton county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
13,1023,AL,choctaw county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
14,1025,AL,clarke county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
15,1027,AL,clay county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
16,1029,AL,cleburne county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
17,1031,AL,coffee county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
18,1033,AL,colbert county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
19,1035,AL,conecuh county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
20,1037,AL,coosa county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
21,1039,AL,covington county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
22,1041,AL,crenshaw county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
23,1043,AL,cullman county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
24,1045,AL,dale county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
25,1047,AL,dallas county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
26,1049,AL,dekalb county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
27,1051,AL,elmore county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
28,1053,AL,escambia county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
29,1055,AL,etowah county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0
...,...,...,...,...,...,...,...,...,...,...,...
3243,72095,PR,"maunabo municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3244,72097,PR,"mayagÃ¼ez municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3245,72099,PR,"moca municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3246,72101,PR,"morovis municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3247,72103,PR,"naguabo municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3248,72105,PR,"naranjito municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3249,72107,PR,"orocovis municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3250,72109,PR,"patillas municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3251,72111,PR,"peÃ±uelas municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3252,72113,PR,"ponce municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3253,72115,PR,"quebradillas municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3254,72117,PR,"rincÃ³n municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3255,72119,PR,"rÃ­o grande municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3256,72121,PR,"sabana grande municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3257,72123,PR,"salinas municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3258,72125,PR,"san germÃ¡n municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3259,72127,PR,"san juan municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3260,72129,PR,"san lorenzo municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3261,72131,PR,"san sebastiÃ¡n municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3262,72133,PR,"santa isabel municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3263,72135,PR,"toa alta municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3264,72137,PR,"toa baja municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3265,72139,PR,"trujillo alto municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3266,72141,PR,"utuado municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3267,72143,PR,"vega alta municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3268,72145,PR,"vega baja municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3269,72147,PR,"vieques municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3270,72149,PR,"villalba municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3271,72151,PR,"yabucoa municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0
3272,72153,PR,"yauco municipio, puerto rico",NaN,NaN,NaN,737500.0,737499.0,737499.0,737500.0,737495.0

In [19]:
#Merging of Mainly Fixed Data

#Merging Policy & Educ, have most rows
Policy_Educ = pd.merge(Educ, Policies, left_on='FIPS', right_on='FIPS')
#Merging with Area Data, also has some extra rows
Policy_Educ_Area = pd.merge(Policy_Educ, Area_Houses, left_on='FIPS', right_on='County FIPS')
#Merging with Health Data
Policy_Educ_Area_Health = pd.merge(Policy_Educ_Area, County_Health, left_on='FIPS', right_on='FIPS')
#Merging with Population Data
Policy_Educ_Area_Health_Pop = pd.merge(Policy_Educ_Area_Health, County_Pop_Pop60, left_on='FIPS', right_on='FIPS')
#Merging with Unemployment Data
Policy_Educ_Area_Health_Pop_Unemp = pd.merge(Policy_Educ_Area_Health_Pop, Unemp, left_on='FIPS', right_on='FIPS')
#Merging with Poverty Data
Policy_Educ_Area_Health_Pop_Unemp_Pov = pd.merge(Policy_Educ_Area_Health_Pop_Unemp, Poverty, left_on='FIPS', right_on='FIPS')
#Merging with Transit Data
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit = pd.merge(Policy_Educ_Area_Health_Pop_Unemp_Pov, Transit, left_on='FIPS', right_on='FIPS')
#Merging with Votes Data
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes = pd.merge(Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit, Votes, left_on='FIPS', right_on='FIPS')

#Same as above DataFrame, dataset of merged Policy, Education, Area, Health, Population, Poverty, Transit, & Voting Data
#Organized by FIPS (Nearly all FIPS codes accounted for)
Merged_Fixed = Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes
Merged_Fixed.to_csv('Merged_Fixed.csv')

#Joining Merged Data with Racial/Age Data (This is incomplete, not all FIPS included)
Merged_Demographics = pd.merge(Merged_Fixed, Age_Race, left_on='FIPS', right_on='FIPS')
Merged_Demographics.to_csv('Merged_Demographics.csv')

In [20]:
print('Policy_Educ: ' + str(len(Policy_Educ)))
print('Policy_Educ_Area: ' + str(len(Policy_Educ_Area)) + '\n')
print('Policy_Educ_Area_Health: ' + str(len(Policy_Educ_Area_Health)))
print('Policy_Educ_Area_Health_Pop: ' + str(len(Policy_Educ_Area_Health_Pop)) + '\n')
print('Policy_Educ_Area_Health_Pop_Unemp: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp)))
print('Policy_Educ_Area_Health_Pop_Unemp_Pov: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_Pov)))
print('Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit)))
print('Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes)) + '\n')
print('Merged_Fixed: ' + str(len(Merged_Fixed)))
print('Merged_Demographics: ' + str(len(Merged_Demographics)))

Policy_Educ: 3273
Policy_Educ_Area: 3218

Policy_Educ_Area_Health: 3141
Policy_Educ_Area_Health_Pop: 3141

Policy_Educ_Area_Health_Pop_Unemp: 3140
Policy_Educ_Area_Health_Pop_Unemp_Pov: 3135
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit: 3134
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes: 3114

Merged_Fixed: 3114
Merged_Demographics: 825

In [21]:
pd.set_option('max_columns', None)
Merged_Fixed.head()

,FIPS,"Less than a high school diploma, 2014-18","High school diploma only, 2014-18","Some college or associate's degree, 2014-18","Bachelor's degree or higher, 2014-18","Percent of adults with less than a high school diploma, 2014-18","Percent of adults with a high school diploma only, 2014-18","Percent of adults completing some college or associate's degree, 2014-18","Percent of adults with a bachelor's degree or higher, 2014-18",STATE,AREA_NAME,stay at home,>50 gatherings,>500 gatherings,public schools,restaurant dine-in,entertainment/gym,federal guidelines,foreign travel ban,County FIPS,County Name,Area in square miles - Total area,Area in square miles - Land area,2010 Density per square mile of land area - Population,2010 Density per square mile of land area - Housing units,Unnamed: 0,state,county,hospitals,staffed_beds,licensed_beds,icu_beds_Pre,icu_beds_Post,total_pop,60plus,State,Area_name_x,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Metro_2013,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2018,Med_HH_Income_Percent_of_State_Total_2018,Stabr,Area_name_y,Rural-urban_Continuum_Code_2003,Urban_Influence_Code_2003,Rural-urban_Continuum_Code_2013,Urban_Influence_Code_2013,POVALL_2018,CI90LBAll_2018,CI90UBALL_2018,PCTPOVALL_2018,CI90LBALLP_2018,CI90UBALLP_2018,POV017_2018,CI90LB017_2018,CI90UB017_2018,PCTPOV017_2018,CI90LB017P_2018,CI90UB017P_2018,POV517_2018,CI90LB517_2018,CI90UB517_2018,PCTPOV517_2018,CI90LB517P_2018,CI90UB517P_2018,MEDHHINC_2018,CI90LBINC_2018,CI90UBINC_2018,Name,Score,TCI+,Jobs+,Trips/Week+,Routes,Transit Shed,Transit,Population,Total_2000,Total_2004,Total_2008,Total_2012,Total_2016,Dem_2000,Dem_2004,Dem_2008,Dem_2012,Dem_2016
0,1001,"4,204","12,119","10,552","10,291",11.3,32.6,28.4,27.7,AL,autauga county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1001,Autauga County,604.39,594.44,91.8,37.2,0,AL,Autauga,1,55.0,85.0,6.0,6,55036,10523,AL,"Autauga County, AL",2,2,1,"25,957","25,015",942,3.6,"$59,338",119.0,AL,Autauga County,2,2,2,2,"7,587","6,334","8,840",13.8,11.5,16.1,"2,509","1,965","3,053",19.3,15.1,23.5,"1,891","1,469","2,313",19.5,15.1,23.9,"59,338","53,628","65,048","autauga county, al",0.0,0.0,0,0,0,0,0,55036,17208.0,20081.0,23641.0,23932.0,24973.0,0.287192,0.236940,0.257730,0.265878,0.237697
1,1003,"14,310","40,579","46,025","46,075",9.7,27.6,31.3,31.3,AL,baldwin county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1003,Baldwin County,2027.31,1589.78,114.6,65.5,1,AL,Baldwin,3,362.0,410.0,44.0,51,203360,53519,AL,"Baldwin County, AL",3,2,1,"93,849","90,456","3,393",3.6,"$57,588",115.5,AL,Baldwin County,4,5,3,2,"21,069","17,390","24,748",9.8,8.1,11.5,"6,442","4,723","8,161",13.9,10.2,17.6,"4,534","3,223","5,845",13.1,9.3,16.9,"57,588","54,437","60,739","baldwin county, al",0.3,0.1,2691,14,1,1,0,203360,56480.0,69320.0,81413.0,85338.0,95215.0,0.247822,0.225029,0.238119,0.215894,0.193856
2,1005,"4,901","6,486","4,566","2,220",27.0,35.7,25.1,12.2,AL,barbour county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1005,Barbour County,904.52,884.88,31.0,13.4,2,AL,Barbour,1,30.0,74.0,5.0,5,26201,6150,AL,"Barbour County, AL",6,6,0,"8,373","7,940",433,5.2,"$34,382",68.9,AL,Barbour County,6,6,6,6,"6,788","5,662","7,914",30.9,25.8,36.0,"2,242","1,788","2,696",43.9,35.0,52.8,"1,411","1,056","1,766",36.7,27.5,45.9,"34,382","31,157","37,607","barbour county, al",0.0,0.0,0,0,0,0,0,26201,10395.0,10777.0,11630.0,11509.0,10469.0,0.499086,0.448362,0.489854,0.513685,0.465278
3,1007,"2,650","7,471","3,846","1,813",16.8,47.3,24.4,11.5,AL,bibb county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1007,Bibb County,626.17,622.58,36.8,14.4,3,AL,Bibb,1,25.0,35.0,0.0,0,22580,4773,AL,"Bibb County, AL",1,1,1,"8,661","8,317",344,4.0,"$46,064",92.3,AL,Bibb County,1,1,1,1,"4,400","3,445","5,355",21.8,17.1,26.5,"1,238",923,"1,553",27.8,20.7,34.9,840,606,"1,074",26.3,19.0,33.6,"46,064","41,283","50,845","bibb county, al",0.1,0.0,279,2,0,0,0,22580,7101.0,7600.0,8644.0,8420.0,8819.0,0.381636,0.274868,0.265965,0.261520,0.212496
4,1009,"7,861","13,489","13,267","5,010",19.8,34.0,33.5,12.6,AL,blount county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1009,Blount County,650.63,644.78,88.9,37.0,4,AL,Blount,1,25.0,40.0,6.0,6,57667,13600,AL,"Blount County, AL",1,1,1,"25,006","24,128",878,3.5,"$50,412",101.1,AL,Blount County,1,1,1,1,"7,527","6,045","9,009",13.2,10.6,15.8,"2,374","1,784","2,964",18.0,13.5,22.5,"1,520","1,053","1,987",15.5,10.7,20.3,"50,412","46,157","54,667","blount county, al",0.0,0.0,0,0,0,0,0,57667,17973.0,21504.0,24267.0,24006.0,25588.0,0.276915,0.183129,0.145135,0.123719,0.084258

In [22]:
list(Merged_Fixed.columns)

['FIPS',
 'Less than a high school diploma, 2014-18',
 'High school diploma only, 2014-18',
 "Some college or associate's degree, 2014-18",
 "Bachelor's degree or higher, 2014-18",
 'Percent of adults with less than a high school diploma, 2014-18',
 'Percent of adults with a high school diploma only, 2014-18',
 "Percent of adults completing some college or associate's degree, 2014-18",
 "Percent of adults with a bachelor's degree or higher, 2014-18",
 'STATE',
 'AREA_NAME',
 'stay at home',
 '>50 gatherings',
 '>500 gatherings',
 'public schools',
 'restaurant dine-in',
 'entertainment/gym',
 'federal guidelines',
 'foreign travel ban',
 'County FIPS',
 'County Name',
 'Area in square miles - Total area',
 'Area in square miles - Land area',
 '2010 Density per square mile of land area - Population',
 '2010 Density per square mile of land area - Housing units',
 'Unnamed: 0',
 'state',
 'county',
 'hospitals',
 'staffed_beds',
 'licensed_beds',
 'icu_beds_Pre',
 'icu_beds_Post',
 'total_pop',
 '60plus',
 'State',
 'Area_name_x',
 'Rural_urban_continuum_code_2013',
 'Urban_influence_code_2013',
 'Metro_2013',
 'Civilian_labor_force_2018',
 'Employed_2018',
 'Unemployed_2018',
 'Unemployment_rate_2018',
 'Median_Household_Income_2018',
 'Med_HH_Income_Percent_of_State_Total_2018',
 'Stabr',
 'Area_name_y',
 'Rural-urban_Continuum_Code_2003',
 'Urban_Influence_Code_2003',
 'Rural-urban_Continuum_Code_2013',
 'Urban_Influence_Code_2013',
 'POVALL_2018',
 'CI90LBAll_2018',
 'CI90UBALL_2018',
 'PCTPOVALL_2018',
 'CI90LBALLP_2018',
 'CI90UBALLP_2018',
 'POV017_2018',
 'CI90LB017_2018',
 'CI90UB017_2018',
 'PCTPOV017_2018',
 'CI90LB017P_2018',
 'CI90UB017P_2018',
 'POV517_2018',
 'CI90LB517_2018',
 'CI90UB517_2018',
 'PCTPOV517_2018',
 'CI90LB517P_2018',
 'CI90UB517P_2018',
 'MEDHHINC_2018',
 'CI90LBINC_2018',
 'CI90UBINC_2018',
 'Name',
 'Score',
 'TCI+',
 'Jobs+',
 'Trips/Week+',
 'Routes',
 'Transit Shed',
 'Transit',
 'Population',
 'Total_2000',
 'Total_2004',
 'Total_2008',
 'Total_2012',
 'Total_2016',
 'Dem_2000',
 'Dem_2004',
 'Dem_2008',
 'Dem_2012',
 'Dem_2016']

In [23]:
Merged_Demographics.head()

,FIPS,"Less than a high school diploma, 2014-18","High school diploma only, 2014-18","Some college or associate's degree, 2014-18","Bachelor's degree or higher, 2014-18","Percent of adults with less than a high school diploma, 2014-18","Percent of adults with a high school diploma only, 2014-18","Percent of adults completing some college or associate's degree, 2014-18","Percent of adults with a bachelor's degree or higher, 2014-18",STATE,AREA_NAME,stay at home,>50 gatherings,>500 gatherings,public schools,restaurant dine-in,entertainment/gym,federal guidelines,foreign travel ban,County FIPS,County Name,Area in square miles - Total area,Area in square miles - Land area,2010 Density per square mile of land area - Population,2010 Density per square mile of land area - Housing units,Unnamed: 0_x,state,county,hospitals,staffed_beds,licensed_beds,icu_beds_Pre,icu_beds_Post,total_pop,60plus,State,Area_name_x,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Metro_2013,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2018,Med_HH_Income_Percent_of_State_Total_2018,Stabr,Area_name_y,Rural-urban_Continuum_Code_2003,Urban_Influence_Code_2003,Rural-urban_Continuum_Code_2013,Urban_Influence_Code_2013,POVALL_2018,CI90LBAll_2018,CI90UBALL_2018,PCTPOVALL_2018,CI90LBALLP_2018,CI90UBALLP_2018,POV017_2018,CI90LB017_2018,CI90UB017_2018,PCTPOV017_2018,CI90LB017P_2018,CI90UB017P_2018,POV517_2018,CI90LB517_2018,CI90UB517_2018,PCTPOV517_2018,CI90LB517P_2018,CI90UB517P_2018,MEDHHINC_2018,CI90LBINC_2018,CI90UBINC_2018,Name,Score,TCI+,Jobs+,Trips/Week+,Routes,Transit Shed,Transit,Population,Total_2000,Total_2004,Total_2008,Total_2012,Total_2016,Dem_2000,Dem_2004,Dem_2008,Dem_2012,Dem_2016,Unnamed: 0_y,Geographic Area Name,Total population,Male,Female,Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 to 84 years,85 years and over,Median age (years),Under 18 years,16 years and over,18 years and over,21 years and over,62 years and over,65 years and over,18 years and over.1,18 years and over!!Male,18 years and over!!Female,65 years and over.1,65 years and over!!Male,65 years and over!!Female,Total population.1,One race,Two or more races,One race.1,Race_1 White,Race_1 Black or African American,Margin of Error!!Race_1 Black or African American,Race_1 American Indian and Alaska Native,Race_1 American Indian and Alaska Native!!Cherokee tribal grouping,Race_1 American Indian and Alaska Native!!Chippewa tribal grouping,Race_1 American Indian and Alaska Native!!Navajo tribal grouping,Race_1 American Indian and Alaska Native!!Sioux tribal grouping,Race_1 Asian,Race_1 Asian!!Asian Indian,Race_1 Asian!!Chinese,Race_1 Asian!!Filipino,Race_1 Asian!!Japanese,Race_1 Asian!!Korean,Race_1 Asian!!Vietnamese,Race_1 Asian!!Other Asian,Race_1 Native Hawaiian and Other Pacific Islander,Race_1 Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Race_1 Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Race_1 Native Hawaiian and Other Pacific Islander!!Samoan,Race_1 Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Race_1 Some other race,Two or more races.1,Race_2+ White and Black or African American,Race_2+ White and American Indian and Alaska Native,Race_2+ White and Asian,Race_2+ Black or African American and American Indian and Alaska Native,Race_Total Total population,Race_Total White,Race_Total Black or African American,Race_Total American Indian and Alaska Native,Race_Total Asian,Race_Total Native Hawaiian and Other Pacific Islander,Race_Total Some other race,Hispanic: Total population,Hispanic: Hispanic or Latino (of any race),Hispanic: Hispanic or Latino (of any race)!!Mexican,Hispanic: Hispanic or Latino (of any race)!!Puerto Rican,Hispanic: Hispanic or Latino (of any race)!!Cuban,Hispanic: Hispanic or Latino (of any race)!!Other Hispanic or Latino,Hispanic: Not Hispanic or Latino,Hispanic: Not Hispanic or Latino!!White alone,Hispanic: Not Hispanic or Latino!!Black or African American alone,Hispanic: Not Hispanic or Latino!!American Indian and Alaska Native alone,Hispanic: Not Hispanic or Latino!!Asian alone,Hispanic: Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Hispanic: Not Hispanic or Latino!!Some other race alone,Hispanic: Not Hispanic or Latino!!Two or more races,Hispanic: Not Hispanic or Latino!!Race_2+ Two races including Some other race,"Hispanic: Not Hispanic or Latino!!Race_2+ Two races excluding Some other race, and Three or more races",Total housing units
0,1003,"14,310","40,579","46,025","46,075",9.7,27.6,31.3,31.3,AL,baldwin county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1003,Baldwin County,2027.31,1589.78,114.6,65.5,1,AL,Baldwin,3,362.0,410.0,44.0,51,203360,53519,AL,"Baldwin County, AL",3,2,1,"93,849","90,456","3,393",3.6,"$57,588",115.5,AL,Baldwin County,4,5,3,2,"21,069","17,390","24,748",9.8,8.1,11.5,"6,442","4,723","8,161",13.9,10.2,17.6,"4,534","3,223","5,845",13.1,9.3,16.9,"57,588","54,437","60,739","baldwin county, al",0.3,0.1,2691,14,1,1,0,203360,56480.0,69320.0,81413.0,85338.0,95215.0,0.247822,0.225029,0.238119,0.215894,0.193856,637,"Baldwin County, Alabama",218022,105437,112585,10878,9445,18093,13489,10426,23498,25990,30117,16569,15074,27152,13464,3827,44.0,47156,176222,170866,163886,53676,44443,170866,81046,89820,44443,20457,23986,218022,214558,3464,214558,187759,20554,446,1276,N,N,N,N,2338,N,N,N,N,N,N,N,45,N,N,N,N,2586,3464,227,2100,739,0,218022,191157,20781,3442,3143,N,2798,218022,10132,5148,1543,321,3120,207890,180926,20328,1209,2338,45,148,2896,127,2769,116632
1,1015,"12,620","25,653","26,643","14,219",15.9,32.4,33.7,18.0,AL,calhoun county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1015,Calhoun County,612.29,605.87,195.7,88.0,7,AL,Calhoun,2,413.0,486.0,24.0,24,115527,27115,AL,"Calhoun County, AL",3,2,1,"45,972","43,833","2,139",4.7,"$45,400",91.0,AL,Calhoun County,3,2,3,2,"21,719","18,807","24,631",19.5,16.9,22.1,"6,397","5,152","7,642",26.5,21.3,31.7,"4,265","3,314","5,216",24.1,18.7,29.5,"45,400","41,668","49,132","calhoun county, al",0.6,0.3,3376,42,1,2,0,115527,38909.0,45249.0,49242.0,46257.0,47864.0,0.405587,0.333333,0.331709,0.335322,0.276659,332,"Calhoun County, Alabama",114277,55054,59223,7142,7158,5968,7386,7451,16273,12608,13616,8305,7855,12240,6514,1761,40.1,24484,93284,89793,84973,24963,20515,89793,42655,47138,20515,8619,11896,114277,111498,2779,111498,85046,24737,642,107,N,N,N,N,426,N,N,N,N,N,N,N,0,N,N,N,N,1182,2779,487,304,767,26,114277,87105,25595,489,1594,N,2024,114277,4469,N,N,N,N,109808,82308,24737,107,426,0,0,2230,293,1937,53888
2,1043,"10,405","20,382","18,559","7,866",18.2,35.6,32.4,13.7,AL,cullman county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1043,Cullman County,755.02,734.84,109.4,50.4,21,AL,Cullman,1,185.0,185.0,12.0,12,81703,19667,AL,"Cullman County, AL",4,3,0,"37,830","36,589","1,241",3.3,"$45,796",91.8,AL,Cullman County,6,3,4,3,"11,925","9,926","13,924",14.5,12.1,16.9,"3,604","2,745","4,463",19.7,15.0,24.4,"2,624","1,953","3,295",19.8,14.7,24.9,"45,796","42,695","48,897","cullman county, al",0.0,0.0,0,0,0,0,0,81703,29525.0,35191.0,35305.0,34457.0,37873.0,0.330500,0.228610,0.166095,0.146618,0.100283,224,"Cullman County, Alabama",83442,40794,42648,5329,4798,5226,5270,4500,10274,10131,10843,5407,6123,9116,5570,855,40.6,18892,66680,64550,61088,18429,15541,64550,31490,33060,15541,7048,8493,83442,81383,2059,81383,78643,906,335,301,N,N,N,N,166,N,N,N,N,N,N,N,0,N,N,N,N,1367,2059,N,N,N,N,83442,80522,1246,1210,903,N,1702,83442,3699,N,N,N,N,79743,N,N,N,N,N,N,N,N,N,38029
3,1049,"12,394","15,956","13,441","6,085",25.9,33.3,28.1,12.7,AL,dekalb county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1049,DeKalb County,778.69,777.09,91.5,40.0,24,AL,De Kalb,1,97.0,134.0,12.0,12,71194,15782,AL,"DeKalb County, AL",6,6,0,"30,129","28,979","1,150",3.8,"$39,491",79.2,AL,DeKalb County,6,6,6,6,"14,975","13,282","16,668",21.3,18.9,23.7,"4,990","4,274","5,706",29.6,25.4,33.8,"3,773","3,275","4,271",29.6,25.7,33.5,"39,491","36,085","42,897","dekalb county, al",0.0,0.0,0,0,0,0,0,71194,20285.0,24135.0,24015.0,23863.0,25826.0,0.347843,0.293847,0.235603,0.219545,0.140246,736,"DeKalb County, Alabama",71385,35048,36337,3989,3851,6121,5079,4176,8645,8261,9548,4533,4921,7377,3342,1542,39.5,17145,57239,54240,51984,15204,12261,54240,26083,28157,12261,5423,6838,71385,70116,1269,70116,60157,1335,201,868,N,N,N,N,173,N,N,N,N,N,N,N,0,N,N,N,N,7583,1269,N,N,N,N,71385,61426,1348,1722,588,N,7583,71385,10595,N,N,N,N,60790,57199,1335,814,173,0,0,1269,0,1269,31656
4,1051,"7,594","18,304","16,197","13,664",13.6,32.8,29.0,24.5,AL,elmore county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1051,Elmore County,657.04,618.48,128.2,52.8,25,AL,Elmore,2,70.0,138.0,5.0,5,80989,15929,AL,"Elmore County, AL",2,2,1,"37,215","35,932","1,283",3.4,"$60,367",121.0,AL,Elmore County,2,2,2,2,"8,559","6,765","10,353",11.2,8.9,13.5,"2,924","2,112","3,736",16.3,11.8,20.8,"2,100","1,463","2,737",15.8,11.0,20.6,"60,367","56,528","64,206","elmore county, al",0.0,0.0,0,0,0,0,0,80989,23804.0,28680.0,34315.0,35485.0,37260.0,0.279449,0.225628,0.241906,0.252332,0.226597,540,"Elmore County, Alabama",81887,39988,41899,5246,4443,5024,5534,4847,12140,10087,11642,5364,5261,7550,3764,985,38.4,18562,65407,63325,61214,15329,12299,63325,30034,33291,12299,5538,6761,81887,79941,1946,79941,60622,17113,1682,345,N,N,N,N,522,N,N,N,N,N,N,N,0,N,N,N,N,1339,1946,N,N,N,N,81887,62491,18388,838,707,N,1395,81887,2467,N,N,N,N,79420,59771,16836,345,522,0,0,1946,56,1890,34416

In [24]:
list(Merged_Demographics.columns)

['FIPS',
 'Less than a high school diploma, 2014-18',
 'High school diploma only, 2014-18',
 "Some college or associate's degree, 2014-18",
 "Bachelor's degree or higher, 2014-18",
 'Percent of adults with less than a high school diploma, 2014-18',
 'Percent of adults with a high school diploma only, 2014-18',
 "Percent of adults completing some college or associate's degree, 2014-18",
 "Percent of adults with a bachelor's degree or higher, 2014-18",
 'STATE',
 'AREA_NAME',
 'stay at home',
 '>50 gatherings',
 '>500 gatherings',
 'public schools',
 'restaurant dine-in',
 'entertainment/gym',
 'federal guidelines',
 'foreign travel ban',
 'County FIPS',
 'County Name',
 'Area in square miles - Total area',
 'Area in square miles - Land area',
 '2010 Density per square mile of land area - Population',
 '2010 Density per square mile of land area - Housing units',
 'Unnamed: 0_x',
 'state',
 'county',
 'hospitals',
 'staffed_beds',
 'licensed_beds',
 'icu_beds_Pre',
 'icu_beds_Post',
 'total_pop',
 '60plus',
 'State',
 'Area_name_x',
 'Rural_urban_continuum_code_2013',
 'Urban_influence_code_2013',
 'Metro_2013',
 'Civilian_labor_force_2018',
 'Employed_2018',
 'Unemployed_2018',
 'Unemployment_rate_2018',
 'Median_Household_Income_2018',
 'Med_HH_Income_Percent_of_State_Total_2018',
 'Stabr',
 'Area_name_y',
 'Rural-urban_Continuum_Code_2003',
 'Urban_Influence_Code_2003',
 'Rural-urban_Continuum_Code_2013',
 'Urban_Influence_Code_2013',
 'POVALL_2018',
 'CI90LBAll_2018',
 'CI90UBALL_2018',
 'PCTPOVALL_2018',
 'CI90LBALLP_2018',
 'CI90UBALLP_2018',
 'POV017_2018',
 'CI90LB017_2018',
 'CI90UB017_2018',
 'PCTPOV017_2018',
 'CI90LB017P_2018',
 'CI90UB017P_2018',
 'POV517_2018',
 'CI90LB517_2018',
 'CI90UB517_2018',
 'PCTPOV517_2018',
 'CI90LB517P_2018',
 'CI90UB517P_2018',
 'MEDHHINC_2018',
 'CI90LBINC_2018',
 'CI90UBINC_2018',
 'Name',
 'Score',
 'TCI+',
 'Jobs+',
 'Trips/Week+',
 'Routes',
 'Transit Shed',
 'Transit',
 'Population',
 'Total_2000',
 'Total_2004',
 'Total_2008',
 'Total_2012',
 'Total_2016',
 'Dem_2000',
 'Dem_2004',
 'Dem_2008',
 'Dem_2012',
 'Dem_2016',
 'Unnamed: 0_y',
 'Geographic Area Name',
 'Total population',
 'Male',
 'Female',
 'Under 5 years',
 '5 to 9 years',
 '10 to 14 years',
 '15 to 19 years',
 '20 to 24 years',
 '25 to 34 years',
 '35 to 44 years',
 '45 to 54 years',
 '55 to 59 years',
 '60 to 64 years',
 '65 to 74 years',
 '75 to 84 years',
 '85 years and over',
 'Median age (years)',
 'Under 18 years',
 '16 years and over',
 '18 years and over',
 '21 years and over',
 '62 years and over',
 '65 years and over',
 '18 years and over.1',
 '18 years and over!!Male',
 '18 years and over!!Female',
 '65 years and over.1',
 '65 years and over!!Male',
 '65 years and over!!Female',
 'Total population.1',
 'One race',
 'Two or more races',
 'One race.1',
 'Race_1 White',
 'Race_1 Black or African American',
 'Margin of Error!!Race_1 Black or African American',
 'Race_1 American Indian and Alaska Native',
 'Race_1 American Indian and Alaska Native!!Cherokee tribal grouping',
 'Race_1 American Indian and Alaska Native!!Chippewa tribal grouping',
 'Race_1 American Indian and Alaska Native!!Navajo tribal grouping',
 'Race_1 American Indian and Alaska Native!!Sioux tribal grouping',
 'Race_1 Asian',
 'Race_1 Asian!!Asian Indian',
 'Race_1 Asian!!Chinese',
 'Race_1 Asian!!Filipino',
 'Race_1 Asian!!Japanese',
 'Race_1 Asian!!Korean',
 'Race_1 Asian!!Vietnamese',
 'Race_1 Asian!!Other Asian',
 'Race_1 Native Hawaiian and Other Pacific Islander',
 'Race_1 Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Race_1 Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Race_1 Native Hawaiian and Other Pacific Islander!!Samoan',
 'Race_1 Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Race_1 Some other race',
 'Two or more races.1',
 'Race_2+ White and Black or African American',
 'Race_2+ White and American Indian and Alaska Native',
 'Race_2+ White and Asian',
 'Race_2+ Black or African American and American Indian and Alaska Native',
 'Race_Total Total population',
 'Race_Total White',
 'Race_Total Black or African American',
 'Race_Total American Indian and Alaska Native',
 'Race_Total Asian',
 'Race_Total Native Hawaiian and Other Pacific Islander',
 'Race_Total Some other race',
 'Hispanic: Total population',
 'Hispanic: Hispanic or Latino (of any race)',
 'Hispanic: Hispanic or Latino (of any race)!!Mexican',
 'Hispanic: Hispanic or Latino (of any race)!!Puerto Rican',
 'Hispanic: Hispanic or Latino (of any race)!!Cuban',
 'Hispanic: Hispanic or Latino (of any race)!!Other Hispanic or Latino',
 'Hispanic: Not Hispanic or Latino',
 'Hispanic: Not Hispanic or Latino!!White alone',
 'Hispanic: Not Hispanic or Latino!!Black or African American alone',
 'Hispanic: Not Hispanic or Latino!!American Indian and Alaska Native alone',
 'Hispanic: Not Hispanic or Latino!!Asian alone',
 'Hispanic: Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone',
 'Hispanic: Not Hispanic or Latino!!Some other race alone',
 'Hispanic: Not Hispanic or Latino!!Two or more races',
 'Hispanic: Not Hispanic or Latino!!Race_2+ Two races including Some other race',
 'Hispanic: Not Hispanic or Latino!!Race_2+ Two races excluding Some other race, and Three or more races',
 'Total housing units']

In [25]:
#Merging of Fixed Data with Death Data

#Merging CD with Policy, Educ, have extra rows
Policy_Educ_CD = pd.merge(Policy_Educ, USAFacts_CDConsecutive, left_on='FIPS', right_on='countyFIPS')
#Merging with Area Data, also has some extra rows
Policy_Educ_Area_CD = pd.merge(Policy_Educ_CD, Area_Houses, left_on='FIPS', right_on='County FIPS')

#Merging with Health Data
Policy_Educ_Area_Health_CD = pd.merge(Policy_Educ_Area_CD, County_Health, left_on='FIPS', right_on='FIPS')
#Merging with Population Data
Policy_Educ_Area_Health_Pop_CD = pd.merge(Policy_Educ_Area_Health_CD, County_Pop_Pop60, left_on='FIPS', right_on='FIPS')
#Merging with Unemployment Data
Policy_Educ_Area_Health_Pop_Unemp_CD = pd.merge(Policy_Educ_Area_Health_Pop_CD, Unemp, left_on='FIPS', right_on='FIPS')
#Merging with Poverty Data
Policy_Educ_Area_Health_Pop_Unemp_Pov_CD = pd.merge(Policy_Educ_Area_Health_Pop_Unemp_CD, Poverty, left_on='FIPS', right_on='FIPS')
#Merging with Transit Data
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_CD = pd.merge(Policy_Educ_Area_Health_Pop_Unemp_Pov_CD, Transit, left_on='FIPS', right_on='FIPS')
#Merging with Votes Data
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes_CD = pd.merge(Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_CD, Votes, left_on='FIPS', right_on='FIPS')


#Making Merged Dataset
Merged_CD = pd.merge(Merged_Fixed, USAFacts_CDConsecutive, left_on='FIPS', right_on='countyFIPS')
Merged_CD.to_csv('Merged_CD.csv')

#Joining Merged Data with Racial/Age Data (This is incomplete, not all FIPS included)
Merged_Demographics_CD = pd.merge(Merged_CD, Age_Race, left_on='FIPS', right_on='FIPS')
Merged_Demographics_CD.to_csv('Merged_Demographics_CD.csv')

In [26]:
print('Policy_Educ_CD: ' + str(len(Policy_Educ_CD)))
print('Policy_Educ_Area_CD: ' + str(len(Policy_Educ_Area_CD)) + '\n')
print('Policy_Educ_Area_Health_CD: ' + str(len(Policy_Educ_Area_Health_CD)))
print('Policy_Educ_Area_Health_Pop_CD: ' + str(len(Policy_Educ_Area_Health_Pop_CD)) + '\n')
print('Policy_Educ_Area_Health_Pop_Unemp_CD: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_CD)))
print('Policy_Educ_Area_Health_Pop_Unemp_Pov_CD: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_Pov_CD)))
print('Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_CD: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_CD)))
print('Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes_CD: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes_CD)) + '\n')
print('Merged_CD: ' + str(len(Merged_CD)))
print('Merged_Demographics_CD: ' + str(len(Merged_Demographics_CD)))

Policy_Educ_CD: 3143
Policy_Educ_Area_CD: 3140

Policy_Educ_Area_Health_CD: 3141
Policy_Educ_Area_Health_Pop_CD: 3141

Policy_Educ_Area_Health_Pop_Unemp_CD: 3140
Policy_Educ_Area_Health_Pop_Unemp_Pov_CD: 3135
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_CD: 3134
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes_CD: 3114

Merged_CD: 3114
Merged_Demographics_CD: 825

In [27]:
Merged_CD.head()

,FIPS,"Less than a high school diploma, 2014-18","High school diploma only, 2014-18","Some college or associate's degree, 2014-18","Bachelor's degree or higher, 2014-18","Percent of adults with less than a high school diploma, 2014-18","Percent of adults with a high school diploma only, 2014-18","Percent of adults completing some college or associate's degree, 2014-18","Percent of adults with a bachelor's degree or higher, 2014-18",STATE,AREA_NAME,stay at home,>50 gatherings,>500 gatherings,public schools,restaurant dine-in,entertainment/gym,federal guidelines,foreign travel ban,County FIPS,County Name,Area in square miles - Total area,Area in square miles - Land area,2010 Density per square mile of land area - Population,2010 Density per square mile of land area - Housing units,Unnamed: 0,state,county,hospitals,staffed_beds,licensed_beds,icu_beds_Pre,icu_beds_Post,total_pop,60plus,State,Area_name_x,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Metro_2013,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2018,Med_HH_Income_Percent_of_State_Total_2018,Stabr,Area_name_y,Rural-urban_Continuum_Code_2003,Urban_Influence_Code_2003,Rural-urban_Continuum_Code_2013,Urban_Influence_Code_2013,POVALL_2018,CI90LBAll_2018,CI90UBALL_2018,PCTPOVALL_2018,CI90LBALLP_2018,CI90UBALLP_2018,POV017_2018,CI90LB017_2018,CI90UB017_2018,PCTPOV017_2018,CI90LB017P_2018,CI90UB017P_2018,POV517_2018,CI90LB517_2018,CI90UB517_2018,PCTPOV517_2018,CI90LB517P_2018,CI90UB517P_2018,MEDHHINC_2018,CI90LBINC_2018,CI90UBINC_2018,Name,Score,TCI+,Jobs+,Trips/Week+,Routes,Transit Shed,Transit,Population,Total_2000,Total_2004,Total_2008,Total_2012,Total_2016,Dem_2000,Dem_2004,Dem_2008,Dem_2012,Dem_2016,countyFIPS,stateFIPS_C,1/22/20_C,1/22/20_D,1/23/20_C,1/23/20_D,1/24/20_C,1/24/20_D,1/25/20_C,1/25/20_D,1/26/20_C,1/26/20_D,1/27/20_C,1/27/20_D,1/28/20_C,1/28/20_D,1/29/20_C,1/29/20_D,1/30/20_C,1/30/20_D,1/31/20_C,1/31/20_D,2/1/20_C,2/1/20_D,2/10/20_C,2/10/20_D,2/11/20_C,2/11/20_D,2/12/20_C,2/12/20_D,2/13/20_C,2/13/20_D,2/14/20_C,2/14/20_D,2/15/20_C,2/15/20_D,2/16/20_C,2/16/20_D,2/17/20_C,2/17/20_D,2/18/20_C,2/18/20_D,2/19/20_C,2/19/20_D,2/2/20_C,2/2/20_D,2/20/20_C,2/20/20_D,2/21/20_C,2/21/20_D,2/22/20_C,2/22/20_D,2/23/20_C,2/23/20_D,2/24/20_C,2/24/20_D,2/25/20_C,2/25/20_D,2/26/20_C,2/26/20_D,2/27/20_C,2/27/20_D,2/28/20_C,2/28/20_D,2/29/20_C,2/29/20_D,2/3/20_C,2/3/20_D,2/4/20_C,2/4/20_D,2/5/20_C,2/5/20_D,2/6/20_C,2/6/20_D,2/7/20_C,2/7/20_D,2/8/20_C,2/8/20_D,2/9/20_C,2/9/20_D,3/1/20_C,3/1/20_D,3/10/20_C,3/10/20_D,3/11/20_C,3/11/20_D,3/12/20_C,3/12/20_D,3/13/20_C,3/13/20_D,3/14/20_C,3/14/20_D,3/15/20_C,3/15/20_D,3/16/20_C,3/16/20_D,3/17/20_C,3/17/20_D,3/18/20_C,3/18/20_D,3/19/20_C,3/19/20_D,3/2/20_C,3/2/20_D,3/20/20_C,3/20/20_D,3/21/20_C,3/21/20_D,3/22/20_C,3/22/20_D,3/23/20_C,3/23/20_D,3/24/20_C,3/24/20_D,3/25/20_C,3/25/20_D,3/26/20_C,3/26/20_D,3/27/20_C,3/27/20_D,3/28/20_C,3/28/20_D,3/29/20_C,3/29/20_D,3/3/20_C,3/3/20_D,3/30/20_C,3/30/20_D,3/31/20_C,3/31/20_D,3/4/20_C,3/4/20_D,3/5/20_C,3/5/20_D,3/6/20_C,3/6/20_D,3/7/20_C,3/7/20_D,3/8/20_C,3/8/20_D,3/9/20_C,3/9/20_D,4/1/20_C,4/1/20_D,4/2/20_C,4/2/20_D,4/3/20_C,4/3/20_D,4/4/20_C,4/4/20_D,4/5/20_C,4/5/20_D,4/6/20_C,4/6/20_D,4/7/20_C,4/7/20_D
0,1001,"4,204","12,119","10,552","10,291",11.3,32.6,28.4,27.7,AL,autauga county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1001,Autauga County,604.39,594.44,91.8,37.2,0,AL,Autauga,1,55.0,85.0,6.0,6,55036,10523,AL,"Autauga County, AL",2,2,1,"25,957","25,015",942,3.6,"$59,338",119.0,AL,Autauga County,2,2,2,2,"7,587","6,334","8,840",13.8,11.5,16.1,"2,509","1,965","3,053",19.3,15.1,23.5,"1,891","1,469","2,313",19.5,15.1,23.9,"59,338","53,628","65,048","autauga county, al",0.0,0.0,0,0,0,0,0,55036,17208.0,20081.0,23641.0,23932.0,24973.0,0.287192,0.236940,0.257730,0.265878,0.237697,1001,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,4,0,6,0,6,0,6,0,6,0,0,0,7,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,10,0,12,0,12,0,12,0,12,0,12,0
1,1003,"14,310","40,579","46,025","46,075",9.7,27.6,31.3,31.3,AL,baldwin county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1003,Baldwin County,2027.31,1589.78,114.6,65.5,1,AL,Baldwin,3,362.0,410.0,44.0,51,203360,53519,AL,"Baldwin County, AL",3,2,1,"93,849","90,456","3,393",3.6,"$57,588",115.5,AL,Baldwin County,4,5,3,2,"21,069","17,390","24,748",9.8,8.1,11.5,"6,442","4,723","8,161",13.9,10.2,17.6,"4,534","3,223","5,845",13.1,9.3,16.9,"57,588","54,437","60,739","baldwin county, al",0.3,0.1,2691,14,1,1,0,203360,56480.0,69320.0,81413.0,85338.0,95215.0,0.247822,0.225029,0.238119,0.215894,0.193856,1003,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,2,0,2,0,3,0,3,0,4,0,4,0,5,0,5,0,10,0,15,0,0,0,18,0,19,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,25,0,28,0,29,0,34,0,38,0,42,0
2,1005,"4,901","6,486","4,566","2,220",27.0,35.7,25.1,12.2,AL,barbour county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1005,Barbour County,904.52,884.88,31.0,13.4,2,AL,Barbour,1,30.0,74.0,5.0,5,26201,6150,AL,"Barbour County, AL",6,6,0,"8,373","7,940",433,5.2,"$34,382",68.9,AL,Barbour County,6,6,6,6,"6,788","5,662","7,914",30.9,25.8,36.0,"2,242","1,788","2,696",43.9,35.0,52.8,"1,411","1,056","1,766",36.7,27.5,45.9,"34,382","31,157","37,607","barbour county, al",0.0,0.0,0,0,0,0,0,26201,10395.0,10777.0,11630.0,11509.0,10469.0,0.499086,0.448362,0.489854,0.513685,0.465278,1005,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2,0,2,0,3,0,3,0
3,1007,"2,650","7,471","3,846","1,813",16.8,47.3,24.4,11.5,AL,bibb county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1007,Bibb County,626.17,622.58,36.8,14.4,3,AL,Bibb,1,25.0,35.0,0.0,0,22580,4773,AL,"Bibb County, AL",1,1,1,"8,661","8,317",344,4.0,"$46,064",92.3,AL,Bibb County,1,1,1,1,"4,400","3,445","5,355",21.8,17.1,26.5,"1,238",923,"1,553",27.8,20.7,34.9,840,606,"1,074",26.3,19.0,33.6,"46,064","41,283","50,845","bibb county, al",0.1,0.0,279,2,0,0,0,22580,7101.0,7600.0,8644.0,8420.0,8819.0,0.381636,0.274868,0.265965,0.261520,0.212496,1007,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,4,0,4,0,4,0,7,0,7,0,8,0
4,1009,"7,861","13,489","13,267","5,010",19.8,34.0,33.5,12.6,AL,blount county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1009,Blount County,650.63,644.78,88.9,37.0,4,AL,Blount,1,25.0,40.0,6.0,6,57667,13600,AL,"Blount County, AL",1,1,1,"25,006","24,128",878,3.5,"$50,412",101.1,AL,Blount County,1,1,1,1,"7,527","6,045","9,009",13.2,10.6,15.8,"2,374","1,784","2,964",18.0,13.5,22.5,"1,520","1,053","1,987",15.5,10.7,20.3,"50,412","46,157","54,667","blount county, al",0.0,0.0,0,0,0,0,0,57667,17973.0,21504.0,24267.0,24006.0,25588.0,0.276915,0.183129,0.145135,0.123719,0.084258,1009,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2,0,5,0,5,0,5,0,0,0,5,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,6,0,9,0,10,0,10,0,10,0,10,0

In [28]:
Merged_Demographics_CD.head()

,FIPS,"Less than a high school diploma, 2014-18","High school diploma only, 2014-18","Some college or associate's degree, 2014-18","Bachelor's degree or higher, 2014-18","Percent of adults with less than a high school diploma, 2014-18","Percent of adults with a high school diploma only, 2014-18","Percent of adults completing some college or associate's degree, 2014-18","Percent of adults with a bachelor's degree or higher, 2014-18",STATE,AREA_NAME,stay at home,>50 gatherings,>500 gatherings,public schools,restaurant dine-in,entertainment/gym,federal guidelines,foreign travel ban,County FIPS,County Name,Area in square miles - Total area,Area in square miles - Land area,2010 Density per square mile of land area - Population,2010 Density per square mile of land area - Housing units,Unnamed: 0_x,state,county,hospitals,staffed_beds,licensed_beds,icu_beds_Pre,icu_beds_Post,total_pop,60plus,State,Area_name_x,Rural_urban_continuum_code_2013,Urban_influence_code_2013,Metro_2013,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2018,Med_HH_Income_Percent_of_State_Total_2018,Stabr,Area_name_y,Rural-urban_Continuum_Code_2003,Urban_Influence_Code_2003,Rural-urban_Continuum_Code_2013,Urban_Influence_Code_2013,POVALL_2018,CI90LBAll_2018,CI90UBALL_2018,PCTPOVALL_2018,CI90LBALLP_2018,CI90UBALLP_2018,POV017_2018,CI90LB017_2018,CI90UB017_2018,PCTPOV017_2018,CI90LB017P_2018,CI90UB017P_2018,POV517_2018,CI90LB517_2018,CI90UB517_2018,PCTPOV517_2018,CI90LB517P_2018,CI90UB517P_2018,MEDHHINC_2018,CI90LBINC_2018,CI90UBINC_2018,Name,Score,TCI+,Jobs+,Trips/Week+,Routes,Transit Shed,Transit,Population,Total_2000,Total_2004,Total_2008,Total_2012,Total_2016,Dem_2000,Dem_2004,Dem_2008,Dem_2012,Dem_2016,countyFIPS,stateFIPS_C,1/22/20_C,1/22/20_D,1/23/20_C,1/23/20_D,1/24/20_C,1/24/20_D,1/25/20_C,1/25/20_D,1/26/20_C,1/26/20_D,1/27/20_C,1/27/20_D,1/28/20_C,1/28/20_D,1/29/20_C,1/29/20_D,1/30/20_C,1/30/20_D,1/31/20_C,1/31/20_D,2/1/20_C,2/1/20_D,2/10/20_C,2/10/20_D,2/11/20_C,2/11/20_D,2/12/20_C,2/12/20_D,2/13/20_C,2/13/20_D,2/14/20_C,2/14/20_D,2/15/20_C,2/15/20_D,2/16/20_C,2/16/20_D,2/17/20_C,2/17/20_D,2/18/20_C,2/18/20_D,2/19/20_C,2/19/20_D,2/2/20_C,2/2/20_D,2/20/20_C,2/20/20_D,2/21/20_C,2/21/20_D,2/22/20_C,2/22/20_D,2/23/20_C,2/23/20_D,2/24/20_C,2/24/20_D,2/25/20_C,2/25/20_D,2/26/20_C,2/26/20_D,2/27/20_C,2/27/20_D,2/28/20_C,2/28/20_D,2/29/20_C,2/29/20_D,2/3/20_C,2/3/20_D,2/4/20_C,2/4/20_D,2/5/20_C,2/5/20_D,2/6/20_C,2/6/20_D,2/7/20_C,2/7/20_D,2/8/20_C,2/8/20_D,2/9/20_C,2/9/20_D,3/1/20_C,3/1/20_D,3/10/20_C,3/10/20_D,3/11/20_C,3/11/20_D,3/12/20_C,3/12/20_D,3/13/20_C,3/13/20_D,3/14/20_C,3/14/20_D,3/15/20_C,3/15/20_D,3/16/20_C,3/16/20_D,3/17/20_C,3/17/20_D,3/18/20_C,3/18/20_D,3/19/20_C,3/19/20_D,3/2/20_C,3/2/20_D,3/20/20_C,3/20/20_D,3/21/20_C,3/21/20_D,3/22/20_C,3/22/20_D,3/23/20_C,3/23/20_D,3/24/20_C,3/24/20_D,3/25/20_C,3/25/20_D,3/26/20_C,3/26/20_D,3/27/20_C,3/27/20_D,3/28/20_C,3/28/20_D,3/29/20_C,3/29/20_D,3/3/20_C,3/3/20_D,3/30/20_C,3/30/20_D,3/31/20_C,3/31/20_D,3/4/20_C,3/4/20_D,3/5/20_C,3/5/20_D,3/6/20_C,3/6/20_D,3/7/20_C,3/7/20_D,3/8/20_C,3/8/20_D,3/9/20_C,3/9/20_D,4/1/20_C,4/1/20_D,4/2/20_C,4/2/20_D,4/3/20_C,4/3/20_D,4/4/20_C,4/4/20_D,4/5/20_C,4/5/20_D,4/6/20_C,4/6/20_D,4/7/20_C,4/7/20_D,Unnamed: 0_y,Geographic Area Name,Total population,Male,Female,Under 5 years,5 to 9 years,10 to 14 years,15 to 19 years,20 to 24 years,25 to 34 years,35 to 44 years,45 to 54 years,55 to 59 years,60 to 64 years,65 to 74 years,75 to 84 years,85 years and over,Median age (years),Under 18 years,16 years and over,18 years and over,21 years and over,62 years and over,65 years and over,18 years and over.1,18 years and over!!Male,18 years and over!!Female,65 years and over.1,65 years and over!!Male,65 years and over!!Female,Total population.1,One race,Two or more races,One race.1,Race_1 White,Race_1 Black or African American,Margin of Error!!Race_1 Black or African American,Race_1 American Indian and Alaska Native,Race_1 American Indian and Alaska Native!!Cherokee tribal grouping,Race_1 American Indian and Alaska Native!!Chippewa tribal grouping,Race_1 American Indian and Alaska Native!!Navajo tribal grouping,Race_1 American Indian and Alaska Native!!Sioux tribal grouping,Race_1 Asian,Race_1 Asian!!Asian Indian,Race_1 Asian!!Chinese,Race_1 Asian!!Filipino,Race_1 Asian!!Japanese,Race_1 Asian!!Korean,Race_1 Asian!!Vietnamese,Race_1 Asian!!Other Asian,Race_1 Native Hawaiian and Other Pacific Islander,Race_1 Native Hawaiian and Other Pacific Islander!!Native Hawaiian,Race_1 Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro,Race_1 Native Hawaiian and Other Pacific Islander!!Samoan,Race_1 Native Hawaiian and Other Pacific Islander!!Other Pacific Islander,Race_1 Some other race,Two or more races.1,Race_2+ White and Black or African American,Race_2+ White and American Indian and Alaska Native,Race_2+ White and Asian,Race_2+ Black or African American and American Indian and Alaska Native,Race_Total Total population,Race_Total White,Race_Total Black or African American,Race_Total American Indian and Alaska Native,Race_Total Asian,Race_Total Native Hawaiian and Other Pacific Islander,Race_Total Some other race,Hispanic: Total population,Hispanic: Hispanic or Latino (of any race),Hispanic: Hispanic or Latino (of any race)!!Mexican,Hispanic: Hispanic or Latino (of any race)!!Puerto Rican,Hispanic: Hispanic or Latino (of any race)!!Cuban,Hispanic: Hispanic or Latino (of any race)!!Other Hispanic or Latino,Hispanic: Not Hispanic or Latino,Hispanic: Not Hispanic or Latino!!White alone,Hispanic: Not Hispanic or Latino!!Black or African American alone,Hispanic: Not Hispanic or Latino!!American Indian and Alaska Native alone,Hispanic: Not Hispanic or Latino!!Asian alone,Hispanic: Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Hispanic: Not Hispanic or Latino!!Some other race alone,Hispanic: Not Hispanic or Latino!!Two or more races,Hispanic: Not Hispanic or Latino!!Race_2+ Two races including Some other race,"Hispanic: Not Hispanic or Latino!!Race_2+ Two races excluding Some other race, and Three or more races",Total housing units
0,1003,"14,310","40,579","46,025","46,075",9.7,27.6,31.3,31.3,AL,baldwin county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1003,Baldwin County,2027.31,1589.78,114.6,65.5,1,AL,Baldwin,3,362.0,410.0,44.0,51,203360,53519,AL,"Baldwin County, AL",3,2,1,"93,849","90,456","3,393",3.6,"$57,588",115.5,AL,Baldwin County,4,5,3,2,"21,069","17,390","24,748",9.8,8.1,11.5,"6,442","4,723","8,161",13.9,10.2,17.6,"4,534","3,223","5,845",13.1,9.3,16.9,"57,588","54,437","60,739","baldwin county, al",0.3,0.1,2691,14,1,1,0,203360,56480.0,69320.0,81413.0,85338.0,95215.0,0.247822,0.225029,0.238119,0.215894,0.193856,1003,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,1,0,0,0,2,0,2,0,3,0,3,0,4,0,4,0,5,0,5,0,10,0,15,0,0,0,18,0,19,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,25,0,28,0,29,0,34,0,38,0,42,0,637,"Baldwin County, Alabama",218022,105437,112585,10878,9445,18093,13489,10426,23498,25990,30117,16569,15074,27152,13464,3827,44.0,47156,176222,170866,163886,53676,44443,170866,81046,89820,44443,20457,23986,218022,214558,3464,214558,187759,20554,446,1276,N,N,N,N,2338,N,N,N,N,N,N,N,45,N,N,N,N,2586,3464,227,2100,739,0,218022,191157,20781,3442,3143,N,2798,218022,10132,5148,1543,321,3120,207890,180926,20328,1209,2338,45,148,2896,127,2769,116632
1,1015,"12,620","25,653","26,643","14,219",15.9,32.4,33.7,18.0,AL,calhoun county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1015,Calhoun County,612.29,605.87,195.7,88.0,7,AL,Calhoun,2,413.0,486.0,24.0,24,115527,27115,AL,"Calhoun County, AL",3,2,1,"45,972","43,833","2,139",4.7,"$45,400",91.0,AL,Calhoun County,3,2,3,2,"21,719","18,807","24,631",19.5,16.9,22.1,"6,397","5,152","7,642",26.5,21.3,31.7,"4,265","3,314","5,216",24.1,18.7,29.5,"45,400","41,668","49,132","calhoun county, al",0.6,0.3,3376,42,1,2,0,115527,38909.0,45249.0,49242.0,46257.0,47864.0,0.405587,0.333333,0.331709,0.335322,0.276659,1015,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0,2,0,2,0,2,0,2,0,2,0,3,0,3,0,3,0,0,0,9,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,12,0,20,0,21,0,24,0,38,0,48,0,332,"Calhoun County, Alabama",114277,55054,59223,7142,7158,5968,7386,7451,16273,12608,13616,8305,7855,12240,6514,1761,40.1,24484,93284,89793,84973,24963,20515,89793,42655,47138,20515,8619,11896,114277,111498,2779,111498,85046,24737,642,107,N,N,N,N,426,N,N,N,N,N,N,N,0,N,N,N,N,1182,2779,487,304,767,26,114277,87105,25595,489,1594,N,2024,114277,4469,N,N,N,N,109808,82308,24737,107,426,0,0,2230,293,1937,53888
2,1043,"10,405","20,382","18,559","7,866",18.2,35.6,32.4,13.7,AL,cullman county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1043,Cullman County,755.02,734.84,109.4,50.4,21,AL,Cullman,1,185.0,185.0,12.0,12,81703,19667,AL,"Cullman County, AL",4,3,0,"37,830","36,589","1,241",3.3,"$45,796",91.8,AL,Cullman County,6,3,4,3,"11,925","9,926","13,924",14.5,12.1,16.9,"3,604","2,745","4,463",19.7,15.0,24.4,"2,624","1,953","3,295",19.8,14.7,24.9,"45,796","42,695","48,897","cullman county, al",0.0,0.0,0,0,0,0,0,81703,29525.0,35191.0,35305.0,34457.0,37873.0,0.330500,0.228610,0.166095,0.146618,0.100283,1043,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2,0,2,0,2,0,3,0,4,0,6,0,7,0,7,0,7,0,0,0,8,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,9,0,15,0,15,0,15,0,20,0,22,0,224,"Cullman County, Alabama",83442,40794,42648,5329,4798,5226,5270,4500,10274,10131,10843,5407,6123,9116,5570,855,40.6,18892,66680,64550,61088,18429,15541,64550,31490,33060,15541,7048,8493,83442,81383,2059,81383,78643,906,335,301,N,N,N,N,166,N,N,N,N,N,N,N,0,N,N,N,N,1367,2059,N,N,N,N,83442,80522,1246,1210,903,N,1702,83442,3699,N,N,N,N,79743,N,N,N,N,N,N,N,N,N,38029
3,1049,"12,394","15,956","13,441","6,085",25.9,33.3,28.1,12.7,AL,dekalb county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1049,DeKalb County,778.69,777.09,91.5,40.0,24,AL,De Kalb,1,97.0,134.0,12.0,12,71194,15782,AL,"DeKalb County, AL",6,6,0,"30,129","28,979","1,150",3.8,"$39,491",79.2,AL,DeKalb County,6,6,6,6,"14,975","13,282","16,668",21.3,18.9,23.7,"4,990","4,274","5,706",29.6,25.4,33.8,"3,773","3,275","4,271",29.6,25.7,33.5,"39,491","36,085","42,897","dekalb county, al",0.0,0.0,0,0,0,0,0,71194,20285.0,24135.0,24015.0,23863.0,25826.0,0.347843,0.293847,0.235603,0.219545,0.140246,1049,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,4,0,4,0,4,0,0,0,4,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,8,0,10,0,13,0,14,0,14,0,14,0,736,"DeKalb County, Alabama",71385,35048,36337,3989,3851,6121,5079,4176,8645,8261,9548,4533,4921,7377,3342,1542,39.5,17145,57239,54240,51984,15204,12261,54240,26083,28157,12261,5423,6838,71385,70116,1269,70116,60157,1335,201,868,N,N,N,N,173,N,N,N,N,N,N,N,0,N,N,N,N,7583,1269,N,N,N,N,71385,61426,1348,1722,588,N,7583,71385,10595,N,N,N,N,60790,57199,1335,814,173,0,0,1269,0,1269,31656
4,1051,"7,594","18,304","16,197","13,664",13.6,32.8,29.0,24.5,AL,elmore county,NaN,737504.0,737497.0,737500.0,737503.0,NaN,737500.0,737495.0,1051,Elmore County,657.04,618.48,128.2,52.8,25,AL,Elmore,2,70.0,138.0,5.0,5,80989,15929,AL,"Elmore County, AL",2,2,1,"37,215","35,932","1,283",3.4,"$60,367",121.0,AL,Elmore County,2,2,2,2,"8,559","6,765","10,353",11.2,8.9,13.5,"2,924","2,112","3,736",16.3,11.8,20.8,"2,100","1,463","2,737",15.8,11.0,20.6,"60,367","56,528","64,206","elmore county, al",0.0,0.0,0,0,0,0,0,80989,23804.0,28680.0,34315.0,35485.0,37260.0,0.279449,0.225628,0.241906,0.252332,0.226597,1051,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,2,0,4,0,5,0,0,0,6,0,6,0,6,0,6,0,8,0,9,0,10,0,12,0,12,0,12,0,0,0,12,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,17,0,19,0,19,0,19,0,20,0,22,0,540,"Elmore County, Alabama",81887,39988,41899,5246,4443,5024,5534,4847,12140,10087,11642,5364,5261,7550,3764,985,38.4,18562,65407,63325,61214,15329,12299,63325,30034,33291,12299,5538,6761,81887,79941,1946,79941,60622,17113,1682,345,N,N,N,N,522,N,N,N,N,N,N,N,0,N,N,N,N,1339,1946,N,N,N,N,81887,62491,18388,838,707,N,1395,81887,2467,N,N,N,N,79420,59771,16836,345,522,0,0,1946,56,1890,34416