In [193]:
import pandas as pd
import numpy as np
import os

In [194]:
County_Pop_Pop60 = pd.read_csv('../../../data/us/demographics/county_populations.csv', encoding='latin1')
Area_Houses = pd.read_csv('../../../data/us/demographics/county_land_areas.csv', encoding='latin1')
Educ = pd.read_csv('../../../data/us/demographics/education.csv', encoding='latin1')
Unemp = pd.read_csv('../../../data/us/demographics/unemployment.csv', delimiter="\t")
Poverty = pd.read_csv('../../../data/us/demographics/poverty.csv', delimiter="\t")

Age_Race = pd.read_csv('Age_Race.csv', encoding='latin1')

Votes = pd.read_csv('Votes.csv', encoding='latin1')
#Cleaning Votes
Votes = Votes.drop([0,1])
Votes.columns = ['FIPS', 'Total_2000', 'Total_2004', 'Total_2008', 'Total_2012', 'Total_2016', \
                 'Dem_2000', 'Dem_2004', 'Dem_2008', 'Dem_2012', 'Dem_2016']
Votes.FIPS = Votes.FIPS.astype(str).astype(float).astype(int)

County_Health = pd.read_csv('County_Health.csv', encoding='latin1')

Policies = pd.read_csv('../../../data/us/other/policies.csv', encoding='latin1')
Transit = pd.read_csv('../../../data/us/other/transit.csv', encoding='latin1')

Policy_Transit = pd.read_csv('Policy_Transit.csv', encoding='latin1')

In [195]:
print('County_Pop_Pop60: ' + str(len(County_Pop_Pop60)))
print('Area_Houses: ' + str(len(Area_Houses)))
print('Educ: ' + str(len(Educ)))
print('Unemp: ' + str(len(Unemp)))
print('Poverty: ' + str(len(Poverty)) + '\n')

print('Votes: ' + str(len(Votes)) + '\n')
print('Age_Race: ' + str(len(Age_Race)) + '\n')

print('County_Health: ' + str(len(County_Health)) + '\n')

print('Policies: ' + str(len(Policies)))
print('Transit: ' + str(len(Transit)) + '\n')
print('Policy_Transit: ' + str(len(Policy_Transit)))

County_Pop_Pop60: 3142
Area_Houses: 3221
Educ: 3283
Unemp: 3141
Poverty: 3136

Votes: 3155

Age_Race: 838

County_Health: 3143

Policies: 3273
Transit: 3139

Policy_Transit: 3134

In [196]:
#Merging Policy & Educ, have most rows
Policy_Educ = pd.merge(Educ, Policies, left_on='FIPS', right_on='FIPS')
#Merging with Area Data, also has some extra rows
Policy_Educ_Area = pd.merge(Policy_Educ, Area_Houses, left_on='FIPS', right_on='County FIPS')
#Merging with Health Data
Policy_Educ_Area_Health = pd.merge(Policy_Educ_Area, County_Health, left_on='FIPS', right_on='FIPS')
#Merging with Population Data
Policy_Educ_Area_Health_Pop = pd.merge(Policy_Educ_Area_Health, County_Pop_Pop60, left_on='FIPS', right_on='FIPS')
#Merging with Unemployment Data
Policy_Educ_Area_Health_Pop_Unemp = pd.merge(Policy_Educ_Area_Health_Pop, Unemp, left_on='FIPS', right_on='FIPS')
#Merging with Poverty Data
Policy_Educ_Area_Health_Pop_Unemp_Pov = pd.merge(Policy_Educ_Area_Health_Pop_Unemp, Poverty, left_on='FIPS', right_on='FIPS')
#Merging with Transit Data
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit = pd.merge(Policy_Educ_Area_Health_Pop_Unemp_Pov, Transit, left_on='FIPS', right_on='FIPS')
#Merging with Votes Data
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes = pd.merge(Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit, Votes, left_on='FIPS', right_on='FIPS')

#Same as above DataFrame, dataset of merged Policy, Education, Area, Health, Population, Poverty, Transit, & Voting Data
#Organized by FIPS (Nearly all FIPS codes accounted for)
Merged_Fixed = Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes
Merged_Fixed.to_csv('Merged_Fixed.csv')

#Joining Merged Data with Racial/Age Data (This is incomplete, not all FIPS included)
Merged_Demographics = pd.merge(Merged_Fixed, Age_Race, left_on='FIPS', right_on='FIPS')
Merged_Demographics.to_csv('Merged_Demographics.csv')

In [197]:
print('Policy_Educ: ' + str(len(Policy_Educ)))
print('Policy_Educ_Area: ' + str(len(Policy_Educ_Area)) + '\n')
print('Policy_Educ_Area_Health: ' + str(len(Policy_Educ_Area_Health)))
print('Policy_Educ_Area_Health_Pop: ' + str(len(Policy_Educ_Area_Health_Pop)) + '\n')
print('Policy_Educ_Area_Health_Pop_Unemp: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp)))
print('Policy_Educ_Area_Health_Pop_Unemp_Pov: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_Pov)))
print('Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit)))
print('Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes: ' + str(len(Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes)) + '\n')
print('Merged_Fixed: ' + str(len(Merged_Fixed)))
print('Merged_Demographics: ' + str(len(Merged_Demographics)))

Policy_Educ: 3273
Policy_Educ_Area: 3218

Policy_Educ_Area_Health: 3141
Policy_Educ_Area_Health_Pop: 3141

Policy_Educ_Area_Health_Pop_Unemp: 3140
Policy_Educ_Area_Health_Pop_Unemp_Pov: 3135
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit: 3134
Policy_Educ_Area_Health_Pop_Unemp_Pov_Transit_Votes: 3114

Merged_Fixed: 3114
Merged_Demographics: 825

In [198]:
Merged_Fixed.head()

,FIPS,"Less than a high school diploma, 2014-18","High school diploma only, 2014-18","Some college or associate's degree, 2014-18","Bachelor's degree or higher, 2014-18","Percent of adults with less than a high school diploma, 2014-18","Percent of adults with a high school diploma only, 2014-18","Percent of adults completing some college or associate's degree, 2014-18","Percent of adults with a bachelor's degree or higher, 2014-18",STATE,...,Total_2000,Total_2004,Total_2008,Total_2012,Total_2016,Dem_2000,Dem_2004,Dem_2008,Dem_2012,Dem_2016
0,1001,"4,204","12,119","10,552","10,291",11.3,32.6,28.4,27.7,AL,...,17208.0,20081.0,23641.0,23932.0,24973.0,0.287192,0.236940,0.257730,0.265878,0.237697
1,1003,"14,310","40,579","46,025","46,075",9.7,27.6,31.3,31.3,AL,...,56480.0,69320.0,81413.0,85338.0,95215.0,0.247822,0.225029,0.238119,0.215894,0.193856
2,1005,"4,901","6,486","4,566","2,220",27.0,35.7,25.1,12.2,AL,...,10395.0,10777.0,11630.0,11509.0,10469.0,0.499086,0.448362,0.489854,0.513685,0.465278
3,1007,"2,650","7,471","3,846","1,813",16.8,47.3,24.4,11.5,AL,...,7101.0,7600.0,8644.0,8420.0,8819.0,0.381636,0.274868,0.265965,0.261520,0.212496
4,1009,"7,861","13,489","13,267","5,010",19.8,34.0,33.5,12.6,AL,...,17973.0,21504.0,24267.0,24006.0,25588.0,0.276915,0.183129,0.145135,0.123719,0.084258

In [199]:
list(Merged_Fixed.columns)

['FIPS',
 'Less than a high school diploma, 2014-18',
 'High school diploma only, 2014-18',
 "Some college or associate's degree, 2014-18",
 "Bachelor's degree or higher, 2014-18",
 'Percent of adults with less than a high school diploma, 2014-18',
 'Percent of adults with a high school diploma only, 2014-18',
 "Percent of adults completing some college or associate's degree, 2014-18",
 "Percent of adults with a bachelor's degree or higher, 2014-18",
 'STATE',
 'AREA_NAME',
 'stay at home',
 '>50 gatherings',
 '>500 gatherings',
 'public schools',
 'restaurant dine-in',
 'entertainment/gym',
 'federal guidelines',
 'foreign travel ban',
 'County FIPS',
 'County Name',
 'Area in square miles - Total area',
 'Area in square miles - Land area',
 '2010 Density per square mile of land area - Population',
 '2010 Density per square mile of land area - Housing units',
 'Unnamed: 0',
 'state',
 'county',
 'hospitals',
 'staffed_beds',
 'licensed_beds',
 'icu_beds_Pre',
 'icu_beds_Post',
 'total_pop',
 '60plus',
 'State',
 'Area_name_x',
 'Rural_urban_continuum_code_2013',
 'Urban_influence_code_2013',
 'Metro_2013',
 'Civilian_labor_force_2018',
 'Employed_2018',
 'Unemployed_2018',
 'Unemployment_rate_2018',
 'Median_Household_Income_2018',
 'Med_HH_Income_Percent_of_State_Total_2018',
 'Stabr',
 'Area_name_y',
 'Rural-urban_Continuum_Code_2003',
 'Urban_Influence_Code_2003',
 'Rural-urban_Continuum_Code_2013',
 'Urban_Influence_Code_2013',
 'POVALL_2018',
 'CI90LBAll_2018',
 'CI90UBALL_2018',
 'PCTPOVALL_2018',
 'CI90LBALLP_2018',
 'CI90UBALLP_2018',
 'POV017_2018',
 'CI90LB017_2018',
 'CI90UB017_2018',
 'PCTPOV017_2018',
 'CI90LB017P_2018',
 'CI90UB017P_2018',
 'POV517_2018',
 'CI90LB517_2018',
 'CI90UB517_2018',
 'PCTPOV517_2018',
 'CI90LB517P_2018',
 'CI90UB517P_2018',
 'MEDHHINC_2018',
 'CI90LBINC_2018',
 'CI90UBINC_2018',
 'Name',
 'Score',
 'TCI+',
 'Jobs+',
 'Trips/Week+',
 'Routes',
 'Transit Shed',
 'Transit',
 'Population',
 'Total_2000',
 'Total_2004',
 'Total_2008',
 'Total_2012',
 'Total_2016',
 'Dem_2000',
 'Dem_2004',
 'Dem_2008',
 'Dem_2012',
 'Dem_2016']

In [200]:
Merged_Demographics.head()

,FIPS,"Less than a high school diploma, 2014-18","High school diploma only, 2014-18","Some college or associate's degree, 2014-18","Bachelor's degree or higher, 2014-18","Percent of adults with less than a high school diploma, 2014-18","Percent of adults with a high school diploma only, 2014-18","Percent of adults completing some college or associate's degree, 2014-18","Percent of adults with a bachelor's degree or higher, 2014-18",STATE,...,Hispanic: Not Hispanic or Latino!!White alone,Hispanic: Not Hispanic or Latino!!Black or African American alone,Hispanic: Not Hispanic or Latino!!American Indian and Alaska Native alone,Hispanic: Not Hispanic or Latino!!Asian alone,Hispanic: Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone,Hispanic: Not Hispanic or Latino!!Some other race alone,Hispanic: Not Hispanic or Latino!!Two or more races,Hispanic: Not Hispanic or Latino!!Race_2+ Two races including Some other race,"Hispanic: Not Hispanic or Latino!!Race_2+ Two races excluding Some other race, and Three or more races",Total housing units
0,1003,"14,310","40,579","46,025","46,075",9.7,27.6,31.3,31.3,AL,...,180926,20328,1209,2338,45,148,2896,127,2769,116632
1,1015,"12,620","25,653","26,643","14,219",15.9,32.4,33.7,18.0,AL,...,82308,24737,107,426,0,0,2230,293,1937,53888
2,1043,"10,405","20,382","18,559","7,866",18.2,35.6,32.4,13.7,AL,...,N,N,N,N,N,N,N,N,N,38029
3,1049,"12,394","15,956","13,441","6,085",25.9,33.3,28.1,12.7,AL,...,57199,1335,814,173,0,0,1269,0,1269,31656
4,1051,"7,594","18,304","16,197","13,664",13.6,32.8,29.0,24.5,AL,...,59771,16836,345,522,0,0,1946,56,1890,34416

In [201]:
list(Merged_Demographics.columns)

['FIPS',
 'Less than a high school diploma, 2014-18',
 'High school diploma only, 2014-18',
 "Some college or associate's degree, 2014-18",
 "Bachelor's degree or higher, 2014-18",
 'Percent of adults with less than a high school diploma, 2014-18',
 'Percent of adults with a high school diploma only, 2014-18',
 "Percent of adults completing some college or associate's degree, 2014-18",
 "Percent of adults with a bachelor's degree or higher, 2014-18",
 'STATE',
 'AREA_NAME',
 'stay at home',
 '>50 gatherings',
 '>500 gatherings',
 'public schools',
 'restaurant dine-in',
 'entertainment/gym',
 'federal guidelines',
 'foreign travel ban',
 'County FIPS',
 'County Name',
 'Area in square miles - Total area',
 'Area in square miles - Land area',
 '2010 Density per square mile of land area - Population',
 '2010 Density per square mile of land area - Housing units',
 'Unnamed: 0_x',
 'state',
 'county',
 'hospitals',
 'staffed_beds',
 'licensed_beds',
 'icu_beds_Pre',
 'icu_beds_Post',
 'total_pop',
 '60plus',
 'State',
 'Area_name_x',
 'Rural_urban_continuum_code_2013',
 'Urban_influence_code_2013',
 'Metro_2013',
 'Civilian_labor_force_2018',
 'Employed_2018',
 'Unemployed_2018',
 'Unemployment_rate_2018',
 'Median_Household_Income_2018',
 'Med_HH_Income_Percent_of_State_Total_2018',
 'Stabr',
 'Area_name_y',
 'Rural-urban_Continuum_Code_2003',
 'Urban_Influence_Code_2003',
 'Rural-urban_Continuum_Code_2013',
 'Urban_Influence_Code_2013',
 'POVALL_2018',
 'CI90LBAll_2018',
 'CI90UBALL_2018',
 'PCTPOVALL_2018',
 'CI90LBALLP_2018',
 'CI90UBALLP_2018',
 'POV017_2018',
 'CI90LB017_2018',
 'CI90UB017_2018',
 'PCTPOV017_2018',
 'CI90LB017P_2018',
 'CI90UB017P_2018',
 'POV517_2018',
 'CI90LB517_2018',
 'CI90UB517_2018',
 'PCTPOV517_2018',
 'CI90LB517P_2018',
 'CI90UB517P_2018',
 'MEDHHINC_2018',
 'CI90LBINC_2018',
 'CI90UBINC_2018',
 'Name',
 'Score',
 'TCI+',
 'Jobs+',
 'Trips/Week+',
 'Routes',
 'Transit Shed',
 'Transit',
 'Population',
 'Total_2000',
 'Total_2004',
 'Total_2008',
 'Total_2012',
 'Total_2016',
 'Dem_2000',
 'Dem_2004',
 'Dem_2008',
 'Dem_2012',
 'Dem_2016',
 'Unnamed: 0_y',
 'Geographic Area Name',
 'Total population',
 'Male',
 'Female',
 'Under 5 years',
 '5 to 9 years',
 '10 to 14 years',
 '15 to 19 years',
 '20 to 24 years',
 '25 to 34 years',
 '35 to 44 years',
 '45 to 54 years',
 '55 to 59 years',
 '60 to 64 years',
 '65 to 74 years',
 '75 to 84 years',
 '85 years and over',
 'Median age (years)',
 'Under 18 years',
 '16 years and over',
 '18 years and over',
 '21 years and over',
 '62 years and over',
 '65 years and over',
 '18 years and over.1',
 '18 years and over!!Male',
 '18 years and over!!Female',
 '65 years and over.1',
 '65 years and over!!Male',
 '65 years and over!!Female',
 'Total population.1',
 'One race',
 'Two or more races',
 'One race.1',
 'Race_1 White',
 'Race_1 Black or African American',
 'Margin of Error!!Race_1 Black or African American',
 'Race_1 American Indian and Alaska Native',
 'Race_1 American Indian and Alaska Native!!Cherokee tribal grouping',
 'Race_1 American Indian and Alaska Native!!Chippewa tribal grouping',
 'Race_1 American Indian and Alaska Native!!Navajo tribal grouping',
 'Race_1 American Indian and Alaska Native!!Sioux tribal grouping',
 'Race_1 Asian',
 'Race_1 Asian!!Asian Indian',
 'Race_1 Asian!!Chinese',
 'Race_1 Asian!!Filipino',
 'Race_1 Asian!!Japanese',
 'Race_1 Asian!!Korean',
 'Race_1 Asian!!Vietnamese',
 'Race_1 Asian!!Other Asian',
 'Race_1 Native Hawaiian and Other Pacific Islander',
 'Race_1 Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
 'Race_1 Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
 'Race_1 Native Hawaiian and Other Pacific Islander!!Samoan',
 'Race_1 Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
 'Race_1 Some other race',
 'Two or more races.1',
 'Race_2+ White and Black or African American',
 'Race_2+ White and American Indian and Alaska Native',
 'Race_2+ White and Asian',
 'Race_2+ Black or African American and American Indian and Alaska Native',
 'Race_Total Total population',
 'Race_Total White',
 'Race_Total Black or African American',
 'Race_Total American Indian and Alaska Native',
 'Race_Total Asian',
 'Race_Total Native Hawaiian and Other Pacific Islander',
 'Race_Total Some other race',
 'Hispanic: Total population',
 'Hispanic: Hispanic or Latino (of any race)',
 'Hispanic: Hispanic or Latino (of any race)!!Mexican',
 'Hispanic: Hispanic or Latino (of any race)!!Puerto Rican',
 'Hispanic: Hispanic or Latino (of any race)!!Cuban',
 'Hispanic: Hispanic or Latino (of any race)!!Other Hispanic or Latino',
 'Hispanic: Not Hispanic or Latino',
 'Hispanic: Not Hispanic or Latino!!White alone',
 'Hispanic: Not Hispanic or Latino!!Black or African American alone',
 'Hispanic: Not Hispanic or Latino!!American Indian and Alaska Native alone',
 'Hispanic: Not Hispanic or Latino!!Asian alone',
 'Hispanic: Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone',
 'Hispanic: Not Hispanic or Latino!!Some other race alone',
 'Hispanic: Not Hispanic or Latino!!Two or more races',
 'Hispanic: Not Hispanic or Latino!!Race_2+ Two races including Some other race',
 'Hispanic: Not Hispanic or Latino!!Race_2+ Two races excluding Some other race, and Three or more races',
 'Total housing units']